### ISSUE TITLE
ocli/octl will exit interactive mode when an incomplete valid command is typed

### ISSUE THREAD

**Issue by vlopezsantoyo** [open-mpi/orcm#100]
Whenever a valid command with incomplete parameters is typed in the interactive shell of the tool (either octl or ocli), the tool will exit the interactive mode instead of printing the help information associated to the command (as instructed by the wikipage):

```
[victor@karate cli-tools]$ ocli
*** WELCOME TO OCLI ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
ocli> queueUnknown command: queue
[victor@karate cli-tools]$ ocli
*** WELCOME TO OCLI ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
ocli> resourceUnknown command: resource

[victor@karate cli-tools]$ octl
*** WELCOME TO OCTL ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
   diag                 Diagnostics
   power                Power Budget
octl> resourceUnknown command: resource

[victor@karate cli-tools]$ octl
*** WELCOME TO OCTL ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
   diag                 Diagnostics
   power                Power Budget
octl> diagUnknown command: diag
```

The expected behavior according to the wikipage is to print help information associated with the command and stay in interactive mode.

**Comment by benmcclelland** [comment]
To get the help information for that command, the user is excepted to type ? not <enter>.  It sounds like we need to update the documentation to be more clear that <enter> is expected to terminate the interactive session.

**Comment by vlopezsantoyo** [comment]
I have verified the latest status of the wiki and it is now explained how completion of commands in interactive mode works.
