### ISSUE TITLE
ORCMD - Execution warms the error but still runs when sensor parameter is passed twice 

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#102]
When sensor parameter is passed twice by mistake to ORCMD, it warns the error but still runs behaving weird. See execution output below:

[pedro@centospedro demo]$ sudo /home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca sensor ipmi -omca sensor dmidata -omca sensor_base_collect_inventory true[sudo] password for pedro: 
---------------------------------------------------------------------------
The following MCA parameter has been listed multiple times on the
command line:
 
  MCA param:   sensor
 
MCA parameters can only be listed once on a command line to ensure there
is no ambiguity as to its value.  Please correct the situation and
try again.
---------------------------------------------------------------------------
[centospedro:30065] FRU Read success!
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    unsupporcmd-model
from the file:
    help-orcm-sensor-pwr.txt
But I couldn't find that topic in the file.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Power sensing was requested, but the topology info
required to verify processor-level support was not
available. This usually means that your system lacks
the required revision level for hwloc.
 
We will continue to operate, but will not monitor power.
--------------------------------------------------------------------------
[centospedro:30065] Sensor 0: PS1 Power In
[centospedro:30065] Sensor 1: PS1 Temperature
[centospedro:30065] 
******************************
Thu Jan  8 13:56:07 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[centospedro:30065] PROC_IS_AGGREGATOR
[centospedro:30065] IPMI_LOG -> Node centospedro not found; Logging credentials
[centospedro:30065] Adding New Node: centospedro, with BMC IP: 0.0.0.0
DB request: store; data:
primary_key=coretemp,ctime=2015-01-08 13:56:12-0600,hostname=centospedro,core 0=33.000000:degrees C,core 1=35.000000:degrees C,core 2=32.000000:degrees C,core 3=31.000000:degrees C,core 4=30.000000:degrees C,core 5=31.000000:degrees C,core 6=29.000000:degrees C,core 7=30.000000:degrees C,core 8=29.000000:degrees C,core 9=27.000000:degrees C,core 10=30.000000:degrees C,core 11=32.000000:degrees C
DB request: store; data:
primary_key=freq,ctime=2015-01-08 13:56:12-0600,hostname=centospedro,core0=3.326000:GHz,core1=1.596000:GHz,core2=3.326000:GHz,core3=1.596000:GHz,core4=3.326000:GHz,core5=1.596000:GHz,core6=3.326000:GHz,core7=1.596000:GHz,core8=3.326000:GHz,core9=1.596000:GHz,core10=3.326000:GHz,core11=1.596000:GHz,core12=3.326000:GHz,core13=1.596000:GHz,core14=3.326000:GHz,core15=1.596000:GHz,core16=3.326000:GHz,core17=1.596000:GHz,core18=3.326000:GHz,core19=1.596000:GHz,core20=3.326000:GHz,core21=1.596000:GHz,core22=3.326000:GHz,core23=1.596000:GHz
DB request: store; data:
primary_key=ipmi,ctime=2015-01-08 13:56:12-0600,nodename=centospedro,BBmanuf_date=08/24/10,BBmanuf=Intel Corporation,BBname=S5520SC,BBserial=QSHV03400472,BBpart=E30682-355
Opening lan connection to node 0.0.0.0 ...
Connecting to node 0.0.0.0
ipmilan_open_session error, rv = -3
ipmilan receive from BMC failed
ipmi_open error = -3
--------------------------------------------------------------------------
A  ipmi-over-lan command failed with the following reason:
 
Aggregator Node:          centospedro
Compute Node:             centospedro
Compute Node BMC IP:      0.0.0.0
BMC UserName:             root
BMC Password:             knc123
BMC Athentication:        4
BMC User Privilege:       4
BMC Cipher:               3
IPMIUTIL Failure Reason: "receive from BMC failed"
--------------------------------------------------------------------------
Opening lan connection to node 0.0.0.0 ...
Connecting to node 0.0.0.0

**Comment by piniguez** [comment]
Same error can be replicated when passing invalid -omca parameter. See execution output below:

[pedro@centospedro demo]$ sudo /home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca somethingwrong true                                                      
[centospedro:31525] FRU Read success!
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    unsupporcmd-model
from the file:
    help-orcm-sensor-pwr.txt
But I couldn't find that topic in the file.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Power sensing was requested, but the topology info
required to verify processor-level support was not
available. This usually means that your system lacks
the required revision level for hwloc.
 
We will continue to operate, but will not monitor power.
--------------------------------------------------------------------------
[centospedro:31525] Sensor 0: PS1 Power In
[centospedro:31525] Sensor 1: PS1 Temperature
[centospedro:31525] 
******************************
Thu Jan  8 14:13:18 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[centospedro:31525] PROC_IS_AGGREGATOR
[centospedro:31525] IPMI_LOG -> Node centospedro not found; Logging credentials
[centospedro:31525] Adding New Node: centospedro, with BMC IP: 0.0.0.0
DB request: store; data:
primary_key=coretemp,ctime=2015-01-08 14:13:24-0600,hostname=centospedro,core 0=34.000000:degrees C,core 1=35.000000:degrees C,core 2=32.000000:degrees C,core 3=31.000000:degrees C,core 4=30.000000:degrees C,core 5=32.000000:degrees C,core 6=29.000000:degrees C,core 7=29.000000:degrees C,core 8=28.000000:degrees C,core 9=27.000000:degrees C,core 10=30.000000:degrees C,core 11=32.000000:degrees C
DB request: store; data:
primary_key=freq,ctime=2015-01-08 14:13:24-0600,hostname=centospedro,core0=3.326000:GHz,core1=1.596000:GHz,core2=3.326000:GHz,core3=1.596000:GHz,core4=3.326000:GHz,core5=1.596000:GHz,core6=3.326000:GHz,core7=1.596000:GHz,core8=3.326000:GHz,core9=1.596000:GHz,core10=3.326000:GHz,core11=1.596000:GHz,core12=3.326000:GHz,core13=1.596000:GHz,core14=3.326000:GHz,core15=1.596000:GHz,core16=3.326000:GHz,core17=1.596000:GHz,core18=3.326000:GHz,core19=1.596000:GHz,core20=3.326000:GHz,core21=1.596000:GHz,core22=3.326000:GHz,core23=1.596000:GHz
DB request: store; data:
primary_key=ipmi,ctime=2015-01-08 14:13:24-0600,nodename=centospedro,BBmanuf_date=08/24/10,BBmanuf=Intel Corporation,BBname=S5520SC,BBserial=QSHV03400472,BBpart=E30682-355
Opening lan connection to node 0.0.0.0 ...
Connecting to node 0.0.0.0
^Cipmilan_cmd interrupt, after bind complete

**Comment by vpedabal** [comment]
Hi Pedro,
Is this 100% reproducible. I see two issues here:
1. Repeating the same mca parameter in the command line while calling orcmd should throw an error and exit instead of trying to proceed further.
2. Somehow, orcmd is unable to read BMC's LAN parameters correctly. Can you run this command and send me the output - 'sudo ipmiutil fru'

**Comment by piniguez** [comment]
Hi Vineet,
  What do you think about focusing this report on issue #1 only to avoid confusions? for issue #2 I will do further research and run experiment requested and file a new independent issue for it, are you agree?

  On the other hand, Yes, this is 100% reproducible and have at least two completely different ways to reproduce (the common factor is that -omca parameter contains an error). 

Here are the two ways reproduce above:

Example 1:
/home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca somethingwrong true

Example2:
sudo /home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca sensor ipmi -omca sensor dmidata -omca sensor_base_collect_inventory true

**Comment by vpedabal** [comment]
Yes Pedro. That sounds good. I'll check with @benmcclelland & @lrrajesh if this is the default behavior of the tool.

**Comment by piniguez** [comment]
Fix verified, ./orcmd now reports help only:
<pre>
[pedro@karate bin]$ ./orcmd --help
Usage: orcmd [OPTIONS]
  Open Resilient Cluster Manager Daemon

   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-s|-site-file|--site-file <arg0>
                         Site configuration file for this orcm chain
-v|--verbose             Be verbose
-V|--version             Print version and exit
   -validate-config|--validate-config
                         Validate site file and exit

Note: To get the list of MCA parameters
  'orcm-info --param <arg0> <arg1>'
                         The first parameter is the
                         framework (or the keyword "all"); the second
                         parameter is the specific component name (or the
                         keyword "all").
</pre>

**Comment by piniguez** [comment]
This the the error reported now, which seems acceptable even though it doesn't informs duplicated sensor mca parameter:
<pre>
[pedro@karate bin]$ sudo ./orcmd -s -omca sensor ipmi -omca sensor dmidata -omca sensor_base_collect_inventory true
./orcmd: Error: unknown option "sensor"
Type './orcmd --help' for usage.
Command line error, use -h to get help.  Error: -43
</pre>

**Comment by piniguez** [comment]
closing issue
