### ISSUE TITLE
OMPI --map-by board causes reentrant event loop

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#106]
Using --map-by board cases reentrant event loop failure:

<pre>
orun --map-by board --np 1 --node 4 hostname
[[8995,0],0]:  session: 27 allocated for the job 
orun_recv - JOB_COMPLETE
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
</pre>

The map-by board appears to not be supported for ompi either and should probably be removed.

**Comment by lrrajesh** [comment]
Removed the may-by board option from the help for now. We will revisit this and add the board support in the next release.

**Comment by vpedabal** [comment]
The fix for this lies in the ORTE layer.

**Comment by noahv** [comment]
Will not be fixed.  -- Noah
