### ISSUE TITLE
ORCM ocli --help does not match wiki; wiki does not mention --gomca.

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#108]
<pre>
/opt/open-rcm/bin/ocli --help
Usage: ocli [OPTIONS]
  Open Resilient Cluster Manager "ocli" Tool
 
   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-v|--verbose             Be Verbose
-V|--version             Show version information
</pre>

**Comment by noahv** [comment]
Also some deltas for osub and orun between the wiki and --help.

**Comment by avilcheslopez** [comment]
I worked on the ocli wiki.  Please feel free to assign this to me and I will look into correcting the wiki.

**Comment by vpedabal** [comment]
Is this fixed?

**Comment by avilcheslopez** [comment]
Updated the ocli wiki page to include the missing options.

**Comment by avilcheslopez** [comment]
Updated the octl wiki page as well.
