### ISSUE TITLE
ORCMD - "orcmd -h" displaying  invalid messages/errors before currently displaying help

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#111]
orcmd is displaying invalid error messages before displaying the proper help when -h parameter is passed.

 See output example:

<pre>
"
[pedro@centospedro demo]$ ~/orcm-internal/bin/orcmd -h
--------------------------------------------------------------------------
Core temperature monitoring was requested, but this node
does not appear to have the required core-level files, or
you lack authority to access them:
 
  Node:  centospedro
 
This usually indicates that the "coretemp" kernel module
has not been loaded. Operation will continue, but core
temperatures will not be monitored.
--------------------------------------------------------------------------
Cannot map memory.
Not superuser (500)
Cannot open an IPMI driver: /dev/imb, /dev/ipmi0, /dev/ipmi/0, 
         or direct driverless.
[centospedro.zpn.intel.com:13464] Unable to collect the current host details
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    unsupporcmd-model
from the file:
    help-orcm-sensor-pwr.txt
But I couldn't find that topic in the file.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Power sensing was requested, but the topology info
required to verify processor-level support was not
available. This usually means that your system lacks
the required revision level for hwloc.
 
We will continue to operate, but will not monitor power.
--------------------------------------------------------------------------
[centospedro.zpn.intel.com:13464] Sensor 0: PS1 Power In
[centospedro.zpn.intel.com:13464] Sensor 1: PS1 Temperature
Usage: orcmd [OPTIONS]
  Open Resilient Cluster Manager Daemon
 
   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-s|-site-file|--site-file <arg0>  
                         Site configuration file for this orcm chain
-v|--verbose             Be verbose
-V|--version             Print version and exit
   -validate-config|--validate-config 
                         Validate site file and exit
[centospedro.zpn.intel.com:13464] IPMI_FINALIZE
"
</pre>

**Comment by lrrajesh** [comment]
I will look in to this and fix this.

**Comment by piniguez** [comment]
Closing issue due to it is now fixed:
<pre>
[pedro@karate bin]$ ./orcmd --help
Usage: orcmd [OPTIONS]
  Open Resilient Cluster Manager Daemon

   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-s|-site-file|--site-file <arg0>
                         Site configuration file for this orcm chain
-v|--verbose             Be verbose
-V|--version             Print version and exit
   -validate-config|--validate-config
                         Validate site file and exit

Note: To get the list of MCA parameters
  'orcm-info --param <arg0> <arg1>'
                         The first parameter is the
                         framework (or the keyword "all"); the second
                         parameter is the specific component name (or the
                         keyword "all").
</pre>
