### ISSUE TITLE
ORCMD - orcmd -omca parameters not documented into the wiki

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#112]
I was trying to figure it out what are the valid values for the orcmd -omca parameter but nothing is documented on the wiki:

"https://github.com/open-mpi/orcm/wiki/3.2.1-orcmd"

Creating this issue looking for a way to get some guidance/help on the wiki for them

**Comment by benmcclelland** [comment]
orcm-info -a

**Comment by lrrajesh** [comment]
Added a line which says this in the wiki.

Run 'orcm-info -a' to look up supported MCA parameters.

**Comment by vpedabal** [comment]
Each developer to check for the relevant MCA parameters they own and update their wiki page.

**Comment by vpedabal** [comment]
I've updated the documentation with the new MCA parameters. @lrrajesh also added a line in the help menu indicating the correct method to grep for a list of available mca parameters, their defaults and their current values from the configuration file.

**Comment by piniguez** [comment]
issue fixed. 
Following line was added to the botton of the wiki link:
"Run 'orcm-info -a' to look up supported MCA parameters."
