### ISSUE TITLE
ORCMD - orcmd -h  is not displaying valid values for -omca

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#113]
orcmd -h is not displaying valid values from -omca. the following experiments were ran without success:

Experiment 1:
    orcmd -h
Results:
     general help is displayed only:
<pre>
Usage: orcmd [OPTIONS]
  Open Resilient Cluster Manager Daemon
 
   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-s|-site-file|--site-file <arg0>  
                         Site configuration file for this orcm chain
-v|--verbose             Be verbose
-V|--version             Print version and exit
   -validate-config|--validate-config 
                         Validate site file and exit
</pre>

Experiment 2:
    orcmd -omca -h

Results:
    help displays missing -omca parameters even though I am trying to find out what are they:
<pre>
     /home/pedro/orcm-internal/bin/orcmd: Error: option "-omca" did not have enough parameters (2)
Type '/home/pedro/orcm-internal/bin/orcmd --help' for usage.
Command line error, use -h to get help.  Error: -43
</pre>

**Comment by lrrajesh** [comment]
Maybe add some text to the help which says run orcm-info to get all supported mca parameters.

**Comment by lrrajesh** [comment]
I will add this to the orcmd help.

**Comment by piniguez** [comment]
closing this issue as already fixed. See current note at the end of the help:

<pre>
[pedro@centospedro bin]$ ./orcmd --help
Usage: orcmd [OPTIONS]
  Open Resilient Cluster Manager Daemon
 
   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
-h|--help                This help message
   -omca|--omca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)
-s|-site-file|--site-file <arg0>  
                         Site configuration file for this orcm chain
-v|--verbose             Be verbose
-V|--version             Print version and exit
   -validate-config|--validate-config 
                         Validate site file and exit
 
Note: To get the list of MCA parameters
  'orcm-info --param <arg0> <arg1>'  
                         The first parameter is the
                         framework (or the keyword "all"); the second
                         parameter is the specific component name (or the
                         keyword "all").
</pre>

<pre>
[pedro@centospedro bin]$ ./orcmd --version
orcmd 0.7.0rc1
</pre>
