### ISSUE TITLE
[RFC] Add a new component under sensors for reading DMI entries

### ISSUE THREAD

**Issue by vpedabal** [open-mpi/orcm#12]
I would like to propose adding a new component under the sensor framework for reading DMI entires that are exported by the BIOS through the SMBIOS tables. Some of the examples are reading the memory components, and their serial numbers, PCI devices and their details, etc.

We will need all this information for storing the inventory details of the compute nodes in the inventory database.

![image](https://cloud.githubusercontent.com/assets/7843618/4084114/7ca55060-2f04-11e4-8f64-ac136fc34c64.png)

![image](https://cloud.githubusercontent.com/assets/7843618/4084115/8044b47c-2f04-11e4-97b8-16ca933ed420.png)

**Comment by noahv** [comment]
Resolved via this and prior commits for dmidata support

commit 4a448ed26dbfc7518705e40d4624dc285bc5da44
Author: Raghavendra Pendyala <raghavendra.p.pendyala@intel.com>
Date:   Tue Aug 18 16:13:16 2015 -0700
 
      Fixing issues as per review comments
