### ISSUE TITLE
ORCM scheduler shows repeated cancel session messages

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#120]
The scheduler cancel logic shows repeated cancel session messages:

<pre>
[master2-sles12.localdomain:08998] scheduler: cancel session : 13
[master2-sles12.localdomain:08998] scheduler: cancel session : 14
[master2-sles12.localdomain:08998] scheduler: cancel session : 9
[master2-sles12.localdomain:08998] scheduler: cancel session : 10
[master2-sles12.localdomain:08998] scheduler: cancel session : 11
[master2-sles12.localdomain:08998] scheduler: cancel session : 12
[master2-sles12.localdomain:08998] scheduler: cancel session : 13
[master2-sles12.localdomain:08998] scheduler: cancel session : 14
</pre>

**Comment by lrrajesh** [comment]
This issue is resolved in v0.7 branch. Please verify this.
The architectural change is not planned for this release.

**Comment by noahv** [comment]
Issue no longer seen.  Thanks,  -- Noah
