### ISSUE TITLE
ORCM Interactive Job Launch using osub -i check for error conditions and handling

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#121]
Interative osub batch jobs do not indicate that the orun job exited with an error condition.

<pre>
[Mon Jan 12 19:15:47 noah@master2-sles12:cluster-tests] [master]  echo "orun hostnamexx" | osub -i 
RECEIVED ALLOC ID 74[[46898,0],0] IShell Start: /bin/sh 
orcmshell%orun hostnamexx
orun_recv - JOB_COMPLETE
--------------------------------------------------------------------------
orun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.
 
NOTE: A common cause for this error is misspelling a orun command
      line parameter option (remember that orun interprets the first
      unrecognized command line token as the executable).
 
Node:       c1
Executable: hostnamexx
--------------------------------------------------------------------------
orcmshell%exit
RECEIVED ALLOC ID 74[[46898,0],0]:  session: 74 completed notify scheduler 
[Mon Jan 12 19:15:52] [master] echo $?
0
</pre>

**Comment by lrrajesh** [comment]
We can discuss this, It is working as designed. In orcmshell it should report the error code and not when you type exit from the shell to parrent shell.

**Comment by noahv** [comment]
This will be addressed in a future enhancement for job accounting to a DB.
