### ISSUE TITLE
ORCM displaying error when asked to monitor coretemp and write to the DB

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#122]
I ran ORCM with the following command:
`orcmd -s orcm-linux.xml --omca sensor heartbeat,coretemp --omca db_odbc_dsn <name of dsn> --omca db_odbc_user <user>:<pwd> --omca db_odbc_table data_sample`

in an aggregator node. Then I started 32 orcmd daemons in some compute nodes and I got the following error:

> [headnode:108690] ***********************************************
[headnode:108690] db:odbc: Unable to record data sample: 
[headnode:108690] SQLExecute returned: -1
[headnode:108690] ODBC error details:
[headnode:108690] Status record: 1
[headnode:108690] SQL state: 23505
[headnode:108690] Native error: 7
[headnode:108690] Message: ERROR: duplicate key value violates unique constraint "data_sample_pkey"
Key (node_id, data_item_id, time_stamp)=(2, 1, 2015-01-13 10:21:23) already exists.;
Error while executing the query
[headnode:108690] ***********************************************
[headnode:108690] 27 more processes have sent help message help-routed-orcm.txt / lost-route
[headnode:108690] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages `

However, when running without asking ORCM to writte to the DB, ORCM runs without any issue:
`orcmd -s orcm-linux.xml --omca sensor heartbeat,coretemp `

> DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:23:56-0800,hostname=headnode,core 0=26.000000:degrees C,core 1=26.000000:degrees C,core 2=19.000000:degrees C,core 3=23.000000:degrees C,core 4=24.000000:degrees C,core 5=28.000000:degrees C,core 6=23.000000:degrees C,core 7=30.000000:degrees C,core 8=26.000000:degrees C,core 9=26.000000:degrees C,core 10=25.000000:degrees C,core 11=21.000000:degrees C,Physical id 0=30.000000:degrees C,core 12=20.000000:degrees C,core 13=21.000000:degrees C,core 14=28.000000:degrees C,core 15=25.000000:degrees C,core 16=31.000000:degrees C,core 17=19.000000:degrees C,core 18=17.000000:degrees C,core 19=23.000000:degrees C,core 20=26.000000:degrees C,core 21=18.000000:degrees C,core 22=22.000000:degrees C,core 23=26.000000:degrees C,Physical id 1=31.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:25:54-0800,hostname=linux,core 0=14.000000:degrees C,core 1=14.000000:degrees C,core 2=14.000000:degrees C,core 3=14.000000:degrees C,core 4=14.000000:degrees C,core 5=14.000000:degrees C,core 6=14.000000:degrees C,core 7=14.000000:degrees C,core 8=14.000000:degrees C,core 9=14.000000:degrees C,core 10=14.000000:degrees C,core 11=14.000000:degrees C,Physical id 0=14.000000:degrees C,core 12=11.000000:degrees C,core 13=11.000000:degrees C,core 14=11.000000:degrees C,core 15=11.000000:degrees C,core 16=11.000000:degrees C,core 17=11.000000:degrees C,core 18=11.000000:degrees C,core 19=11.000000:degrees C,core 20=11.000000:degrees C,core 21=11.000000:degrees C,core 22=11.000000:degrees C,core 23=19.000000:degrees C,Physical id 1=21.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:25:58-0800,hostname=linux,core 0=18.000000:degrees C,core 1=18.000000:degrees C,core 2=18.000000:degrees C,core 3=18.000000:degrees C,core 4=18.000000:degrees C,core 5=18.000000:degrees C,core 6=18.000000:degrees C,core 7=18.000000:degrees C,core 8=18.000000:degrees C,core 9=18.000000:degrees C,core 10=18.000000:degrees C,core 11=18.000000:degrees C,Physical id 0=19.000000:degrees C,core 12=13.000000:degrees C,core 13=13.000000:degrees C,core 14=13.000000:degrees C,core 15=13.000000:degrees C,core 16=13.000000:degrees C,core 17=13.000000:degrees C,core 18=13.000000:degrees C,core 19=13.000000:degrees C,core 20=13.000000:degrees C,core 21=13.000000:degrees C,core 22=13.000000:degrees C,core 23=13.000000:degrees C,Physical id 1=14.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:25:58-0800,hostname=linux,core 0=21.000000:degrees C,core 1=21.000000:degrees C,core 2=21.000000:degrees C,core 3=21.000000:degrees C,core 4=21.000000:degrees C,core 5=21.000000:degrees C,core 6=21.000000:degrees C,core 7=21.000000:degrees C,core 8=21.000000:degrees C,core 9=20.000000:degrees C,core 10=20.000000:degrees C,core 11=20.000000:degrees C,Physical id 0=21.000000:degrees C,core 12=13.000000:degrees C,core 13=13.000000:degrees C,core 14=13.000000:degrees C,core 15=13.000000:degrees C,core 16=13.000000:degrees C,core 17=13.000000:degrees C,core 18=13.000000:degrees C,core 19=24.000000:degrees C,core 20=14.000000:degrees C,core 21=20.000000:degrees C,core 22=14.000000:degrees C,core 23=17.000000:degrees C,Physical id 1=24.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:26:01-0800,hostname=linux,core 0=22.000000:degrees C,core 1=22.000000:degrees C,core 2=22.000000:degrees C,core 3=22.000000:degrees C,core 4=22.000000:degrees C,core 5=22.000000:degrees C,core 6=22.000000:degrees C,core 7=22.000000:degrees C,core 8=22.000000:degrees C,core 9=22.000000:degrees C,core 10=22.000000:degrees C,core 11=22.000000:degrees C,Physical id 0=24.000000:degrees C,core 12=17.000000:degrees C,core 13=17.000000:degrees C,core 14=17.000000:degrees C,core 15=17.000000:degrees C,core 16=12.000000:degrees C,core 17=21.000000:degrees C,core 18=16.000000:degrees C,core 19=10.000000:degrees C,core 20=19.000000:degrees C,core 21=23.000000:degrees C,core 22=13.000000:degrees C,core 23=21.000000:degrees C,Physical id 1=23.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:26:00-0800,hostname=linux,core 0=10.000000:degrees C,core 1=10.000000:degrees C,core 2=10.000000:degrees C,core 3=10.000000:degrees C,core 4=10.000000:degrees C,core 5=10.000000:degrees C,core 6=10.000000:degrees C,core 7=10.000000:degrees C,core 8=10.000000:degrees C,core 9=10.000000:degrees C,core 10=10.000000:degrees C,core 11=10.000000:degrees C,Physical id 0=10.000000:degrees C,core 12=14.000000:degrees C,core 13=14.000000:degrees C,core 14=14.000000:degrees C,core 15=16.000000:degrees C,core 16=11.000000:degrees C,core 17=9.000000:degrees C,core 18=15.000000:degrees C,core 19=18.000000:degrees C,core 20=22.000000:degrees C,core 21=14.000000:degrees C,core 22=17.000000:degrees C,core 23=15.000000:degrees C,Physical id 1=22.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:26:00-0800,hostname=linux,core 0=18.000000:degrees C,core 1=18.000000:degrees C,core 2=18.000000:degrees C,core 3=18.000000:degrees C,core 4=18.000000:degrees C,core 5=18.000000:degrees C,core 6=18.000000:degrees C,core 7=18.000000:degrees C,core 8=18.000000:degrees C,core 9=18.000000:degrees C,core 10=18.000000:degrees C,core 11=18.000000:degrees C,Physical id 0=18.000000:degrees C,core 12=16.000000:degrees C,core 13=16.000000:degrees C,core 14=16.000000:degrees C,core 15=16.000000:degrees C,core 16=16.000000:degrees C,core 17=16.000000:degrees C,core 18=16.000000:degrees C,core 19=16.000000:degrees C,core 20=16.000000:degrees C,core 21=16.000000:degrees C,core 22=11.000000:degrees C,core 23=24.000000:degrees C,Physical id 1=28.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:26:04-0800,hostname=linux,core 0=16.000000:degrees C,core 1=16.000000:degrees C,core 2=16.000000:degrees C,core 3=16.000000:degrees C,core 4=16.000000:degrees C,core 5=16.000000:degrees C,core 6=16.000000:degrees C,core 7=16.000000:degrees C,core 8=16.000000:degrees C,core 9=16.000000:degrees C,core 10=16.000000:degrees C,core 11=16.000000:degrees C,Physical id 0=17.000000:degrees C,core 12=23.000000:degrees C,core 13=23.000000:degrees C,core 14=23.000000:degrees C,core 15=23.000000:degrees C,core 16=23.000000:degrees C,core 17=23.000000:degrees C,core 18=23.000000:degrees C,core 19=23.000000:degrees C,core 20=23.000000:degrees C,core 21=23.000000:degrees C,core 22=23.000000:degrees C,core 23=23.000000:degrees C,Physical id 1=24.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:25:53-0800,hostname=linux,core 0=16.000000:degrees C,core 1=16.000000:degrees C,core 2=16.000000:degrees C,core 3=16.000000:degrees C,core 4=16.000000:degrees C,core 5=16.000000:degrees C,core 6=16.000000:degrees C,core 7=16.000000:degrees C,core 8=16.000000:degrees C,core 9=16.000000:degrees C,core 10=16.000000:degrees C,core 11=16.000000:degrees C,Physical id 0=16.000000:degrees C,core 12=21.000000:degrees C,core 13=21.000000:degrees C,core 14=21.000000:degrees C,core 15=21.000000:degrees C,core 16=21.000000:degrees C,core 17=21.000000:degrees C,core 18=21.000000:degrees C,core 19=21.000000:degrees C,core 20=21.000000:degrees C,core 21=21.000000:degrees C,core 22=23.000000:degrees C,core 23=20.000000:degrees C,Physical id 1=23.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:26:03-0800,hostname=linux,core 0=18.000000:degrees C,core 1=18.000000:degrees C,core 2=18.000000:degrees C,core 3=18.000000:degrees C,core 4=18.000000:degrees C,core 5=18.000000:degrees C,core 6=18.000000:degrees C,core 7=18.000000:degrees C,core 8=18.000000:degrees C,core 9=18.000000:degrees C,core 10=18.000000:degrees C,core 11=18.000000:degrees C,Physical id 0=19.000000:degrees C,core 12=14.000000:degrees C,core 13=14.000000:degrees C,core 14=14.000000:degrees C,core 15=14.000000:degrees C,core 16=14.000000:degrees C,core 17=14.000000:degrees C,core 18=14.000000:degrees C,core 19=14.000000:degrees C,core 20=14.000000:degrees C,core 21=14.000000:degrees C,core 22=18.000000:degrees C,core 23=16.000000:degrees C,Physical id 1=23.000000:degrees C
DB request: store; data:
primary_key=coretemp,ctime=2015-01-13 10:25:57-0800,hostname=linux,core 0=20.000000:degrees C,core 1=19.000000:degrees C,core 2=19.000000:degrees C,core 3=19.000000:degrees C,core 4=19.000000:degrees C,core 5=19.000000:degrees C,core 6=19.000000:degrees C,core 7=19.000000:degrees C,core 8=19.000000:degrees C,core 9=19.000000:degrees C,core 10=19.000000:degrees C,core 11=18.000000:degrees C,Physical id 0=20.000000:degrees C,core 12=22.000000:degrees C,core 13=22.000000:degrees C,core 14=22.000000:degrees C,core 15=22.000000:degrees C,core 16=22.000000:degrees C,core 17=21.000000:degrees C,core 18=22.000000:degrees C,core 19=15.000000:degrees C,core 20=15.000000:degrees C,core 21=14.000000:degrees C,core 22=14.000000:degrees C,core 23=22.000000:degrees C,Physical id 1=22.000000:degrees C
...

**Comment by vpedabal** [comment]
David to look at the /etc/hosts and verify each compute node has a unique hostname associated to it's IP address

**Comment by forzaclaudio** [comment]
This is an excerpt of the /etc/hosts file:
>192.168.0.1     headnode headnode
###ALL ENTRIES BELOW THIS LINE WILL BE OVERWRITTEN BY WAREWULF ###
#
#See provision.conf for configuration paramaters
#Node Entry for node: node01.cluster (ID=71)
192.168.0.5             node01.cluster node01 node01-eth0.cluster node01-eth0
#Node Entry for node: node01-mic0.cluster (ID=72)
192.168.0.6             node01-mic0.cluster node01-mic0 node01-mic0-eth0.cluster node01-mic0-eth0
#Node Entry for node: node01-mic1.cluster (ID=73)
192.168.0.7             node01-mic1.cluster node01-mic1 node01-mic1-eth0.cluster node01-mic1-eth0
#Node Entry for node: node02.cluster (ID=74)
192.168.0.10            node02.cluster node02 node02-eth0.cluster node02-eth0`
...
#Node Entry for node: node32.cluster (ID=164)
192.168.0.160           node32.cluster node32 node32-eth0.cluster node32-eth0
#Node Entry for node: node32-mic0.cluster (ID=165)
192.168.0.161           node32-mic0.cluster node32-mic0 node32-mic0-eth0.cluster node32-mic0-eth0
#Node Entry for node: node32-mic1.cluster (ID=166)
192.168.0.162           node32-mic1.cluster node32-mic1 node32-mic1-eth0.cluster node32-mic1-eth0

as  you can see, all IP's have unique names. I double checked it and I'm able to log into any nodes using only the hostname e.g. node01, node32, etc. My guess is that maybe the way ORCM gets the name of a host is not working as expected.

**Comment by avilcheslopez** [comment]
Judging by the data being printed by the db/print component, I suspect the issue is at the source.  So, you've discarded the issue was in the hosts file.  Let's keep narrowing it down by looking into ORCM.

Try the following: run your test again (directing the data to the db/print component to avoid any errors), but increase verbosity in the sensor framework.  The sensor/coretemp sample function (for example) has a message printed at verbosity level of at least 3 which mentions the hostname, and it gets it from the ORTE process info.

This should help us narrow it down.

**Comment by forzaclaudio** [comment]
I did some configuration sanity tests and I found the following:

>#pdsh -w ssh:node[01-32] hostname | sort
node01: linux
node02: linux
node03: linux
node04: linux
node05: linux
node06: linux
node07: linux
node08: linux
node09: linux
node10: linux
node11: linux
node12: linux
node13: linux
node14: linux
node15: linux
node16: linux
node17: linux
node18: linux
node19: linux
node20: linux
node21: linux
node22: linux
node23: linux
node24: linux
node25: linux
node26: linux
node27: linux
node28: linux
node29: linux
node30: linux
node31: linux
node32: linux

hostname in command in all nodes return the **SAME** hostname!
After I renamed all nodes to the right values the problem dissapeared and ORCM logged values into the DB without any unknown issue.
>#pdsh -w ssh:node[01-32] hostname | sort
node01: node01
node02: node02
node03: node03
node04: node04
node05: node05
node06: node06
node07: node07
node08: node08
node09: node09
node10: node10
node11: node11
node12: node12
node13: node13
node14: node14
node15: node15
node16: node16
node17: node17
node18: node18
node19: node19
node20: node20
node21: node21
node22: node22
node23: node23
node24: node24
node25: node25
node26: node26
node27: node27
node28: node28
node29: node29
node30: node30
node31: node31
node32: node32

I don't know the exact mechanism ORCM daemons use to figure out the hostname is running in, but I believe is not ORCM's job to check if the system is running on is setup properly. However, it we document that some basic sanity setup tests must be performed before attempting to run ORCM e.g. some cluster checker tool, we should be OK. Otherwise we will be scratching our heads over and over again with this sort of issues.

**Comment by vpedabal** [comment]
It is expected that all nodes will have unique hostnames. However if you insist on maintain this somewhere, an ideal place would be to start collecting FAQs and add sections on what to be done, if user sees some error. 

Is it possible for the validation team to maintain it, since they are the first persons to find/face issues and understand the solution?

**Comment by avilcheslopez** [comment]
Added some notes to the troubleshooting section (2.1.10) of the wiki.

**Comment by forzaclaudio** [comment]
Documentation has been verified. Thanks a lot!
