### ISSUE TITLE
ORCM aggregator becomes irresponsive to a request to finish and keeps logging data into  the DB

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#124]
ORCM ocassionally becomes irresponsive to a request to finish via ctrl+c and keeps logging data into the DB.

>[headnode:110138] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
^C^C^C^C
^C
^C
^C
^C
^C^C^C
^C^C^C^C^C
^C
^C
^C
^C
^C
^C
^C
^C

Had to start another session to successfully kill orcm

>headnode:/home/test/DB/ALL # ps -a
headnode:/home/test/DB/ALL # ps -a
   PID TTY          TIME CMD
108527 pts/2    00:00:02 isql
110322 pts/1    00:00:01 orcmd
110406 pts/4    00:00:00 ps
headnode:/home/test/DB/ALL # kill -9 110322
headnode:/home/test/DB/ALL # ps -a
   PID TTY          TIME CMD
108527 pts/2    00:00:02 isql
110407 pts/4    00:00:00 ps
Killed

ORCM was being run remotely trough a ssh session

**Comment by benmcclelland** [comment]
Im going to close this one and track this in issue #104 since it seems to be the same issue 
https://github.com/open-mpi/orcm/issues/104
