### ISSUE TITLE
ORCM returns to shell but keeps running in background and logging data into DB

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#125]
When trying to reproduce Issue #124,  I meant to run an ORCM aggregator and redirect stderr into stdin in bash and use pipes to store output in a log file with the following command:

`headnode:/home/test/DB/ALL # /opt/orcm-rc0/bin/orcmd -s orcm-linux.xml --omca sensor heartbeat,coretemp --omca db_odbc_dsn <name of dsn> --omca db_odbc_user <user>:<pwd> --omca db_odbc_table data_sample &2>1 | tee Issue1b.log`

then I launched some ORCM daemon in some compute nodes, with the command:
`headnode:/home/test/DB/ALL # /opt/orcm-rc0/bin/orcmd -s orcm-linux.xml --omca sensor heartbeat,coretemp`

First thing, I notice is that the redirection part is mistyped should have been 2>&1 and I kill the running ORCM aggregator and this takes me back to the shell. However, the ORCM daemon was still running in the background, keeping logging data into the DB. Had to search for ORCM´s PID and kill it manually. I could only know that ORCM didn´t die because the ORCM daemons in the compute nodes were still running after I ctrl+c 'ed the aggregator.

**Comment by vpedabal** [comment]
Doesn't seem to be an issue as it seems the orcmd is being launched as a bg process
