### ISSUE TITLE
ORCM Inventory Gathering -- Test Vector Support --

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#136]
Hi Vineet,

Please add an orcmd test vector for inventory gathering so that we can can restart orcmd on a targeted compute node and have it report back an identifiable inventory change (via the requested test vector) for the baseboard inventory as well as the CPU inventory.

**Comment by piniguez** [comment]
Hi guys,
      The test vector update in the database works fine and console works fine. So this issue is ready to close it.

Note:
     In this case it is observed VALUE_REAL with weird format, this is already addressed in another issue #140.

CONSOLE OUTPUT:
<pre>
[pedro@centospedro sensors]$ sudo ~/orcm-v07/bin/orcmd -omca sensor dmidata,ipmi -omca sensor_base_collect_inventory true -omca sensor_base_collect_metrics false
[sudo] password for pedro: 
[centospedro:29714] FRU Read success!
[centospedro:29714] Sensor 0: PS1 Power In
[centospedro:29714] Sensor 1: PS1 Temperature
[centospedro:29714] 
******************************
Mon Jan 26 12:39:44 2015: ORCM version: 0.7.0rc1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: update_node_features; data:
hostname=centospedro,product_uuid=9D556D01-B540-11DF-BD28-000BAB01F3E0,bb_vendor=Intel Corporation,bb_model=S5520SC,bb_version=E30682-355,bb_serial=QSHV03400472,bios_vendor=Intel Corp.,bios_version=S5500.86B.01.X2.0059.091520111722,bios_release_date=09/15/2011,num_sockets=2,cpu_vendor=GenuineIntel,cpu_family=6,cpu_model_number=44,cpu_model=Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
DB request: update_node_features; data:
hostname=centospedro,bmc_ver=0.550000,ipmi_ver=2.000000,bb_serial=QSHV03400472,bb_vendor=Intel Corporation,bb_manufactured_date=08/30/10
DB request: update_node_features; data:
hostname=karate,product_uuid=TV_PrUuid,bb_vendor=TV_BbVen,bb_model=TV_BbMod,bb_version=TV_BbVer,bb_serial=TV_BbSer,bios_vendor=TV_BiVen,bios_version=TV_BiVer,bios_release_date=TV_BiRelDat,num_sockets=2,cpu_vendor=TV_CpVen,cpu_family=987,cpu_model_number=654,cpu_model=TV_CpMod
DB request: update_node_features; data:
hostname=karate,bb_manufactured_date=TV_MaufDat,bb_vendor=TV_BbVen,bb_serial=TV_BbSer,ipmi_ver=8.800000,bmc_ver=9.900000
--------------------------------------------------------------------------
</pre>

DATABASE OUTPUT:
<pre>
SQL> select * from node_features_view where hostname='karate'                                                                                                                               
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+-----------------------+-----------------------------------------------------------------------------------------------------+---------------------------------------------------+
| node_id    | hostname                                                                                                                                                                                                                                                       | feature_id | feature                                                                                                                                                                                                                                                   | value_int           | value_real            | value_str                                                                                           | units                                             |
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+-----------------------+-----------------------------------------------------------------------------------------------------+---------------------------------------------------+
| 2          | karate                                                                                                                                                                                                                                                         | 1          | product_uuid                                                                                                                                                                                                                                              |                     |                       | TV_PrUuid                                                                                           |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 3          | bb_model                                                                                                                                                                                                                                                  |                     |                       | TV_BbMod                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 4          | bb_version                                                                                                                                                                                                                                                |                     |                       | TV_BbVer                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 6          | bios_vendor                                                                                                                                                                                                                                               |                     |                       | TV_BiVen                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 7          | bios_version                                                                                                                                                                                                                                              |                     |                       | TV_BiVer                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 8          | bios_release_date                                                                                                                                                                                                                                         |                     |                       | TV_BiRelDat                                                                                         |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 9          | num_sockets                                                                                                                                                                                                                                               | 2                   |                       |                                                                                                     |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 10         | cpu_vendor                                                                                                                                                                                                                                                |                     |                       | TV_CpVen                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 11         | cpu_family                                                                                                                                                                                                                                                | 987                 |                       |                                                                                                     |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 12         | cpu_model_number                                                                                                                                                                                                                                          | 654                 |                       |                                                                                                     |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 13         | cpu_model                                                                                                                                                                                                                                                 |                     |                       | TV_CpMod                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 14         | bb_manufactured_date                                                                                                                                                                                                                                      |                     |                       | TV_MaufDat                                                                                          |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 2          | bb_vendor                                                                                                                                                                                                                                                 |                     |                       | TV_BbVen                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 5          | bb_serial                                                                                                                                                                                                                                                 |                     |                       | TV_BbSer                                                                                            |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 15         | ipmi_ver                                                                                                                                                                                                                                                  |                     | 8.8000001907348597    |                                                                                                     |                                                   |
| 2          | karate                                                                                                                                                                                                                                                         | 16         | bmc_ver                                                                                                                                                                                                                                                   |                     | 9.8999996185302699    |                                                                                                     |                                                   |
+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+-----------------------+-----------------------------------------------------------------------------------------------------+---------------------------------------------------+
SQLRowCount returns 16
16 rows fetched
SQL> 
</pre>

**Comment by piniguez** [comment]
Hi guys,
        During the automated test implementation I realize there is still an issue:
There is not value on test vector for num_sockets due to the number 2 is the current platform sockets!.

Please let me know if want to remove fixed tag for this or open a new one focused on this finding only.

**Comment by vpedabal** [comment]
That's one item which isn't easy to setup a test Vector, it involves merging multiple topologies and creating one. Which at this point I am not entirely familiar with. I would suggest closing out this bug. And filing a new one to add the number of sockets in test vector. We'll mark it for the next release and work on it. Sound ok?

**Comment by piniguez** [comment]
This functionality was already tested in V07 and except for sockets number (will open a new issue to track this) the rest of the fields works fine. Closing this issue.
