### ISSUE TITLE
ORCMD - Inventory Gathering - Numeric fields for Inventory not stored in the proper format

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#140]
Inventorying gathering is storing numeric fields as string values on database. This needs to be changed to the proper format (VALUE_INT, or VALUE_REAL). The following are fields on question:

<pre>
cpu_family -> int
cpu_model_number -> int
bmc_version -> Float
ipmi_version -> Float
</pre>

**Comment by piniguez** [comment]
Code fix test but not 100% funcional. Here is the results:
1. CPU_FAMILY ==> INT (ok)
2. CPU_MODEL_NUMBER ==> INT (ok)
3. BMC_VERSION ==> FLOAT (ok with issues, it is float but storage format = 2, instead of 2.0)
4. IPMI_VERSION ==> FLOAT (ok with issues, it is float but storage format = 0.55000001192092896 instead of 0.55)

Removing Fixed Label..

**Comment by vpedabal** [comment]
@avilcheslopez : I seem to be passing the correct value to the db API. Do you think there is something wrong while storing it in the database?

**Comment by piniguez** [comment]
Hi, I guess what is happenning is the following:
orcm ==> 
          a) reads inventory floating value as string, so this have fixed floating point decimals which varies between fields.
          b) converts them to float
          c) request db to store float value
database ==> 
          d) stores the floating value.

The potential root cause is that on c) there is not way to control the number of decimals to be stored, so we get very weird value when store them on the database....

Later on validation we compare the exact values matches but it follows similar process...

So I wonder if:
1) in order to compare the float values the code that reads the value must add intelligence to convert back to str with limited decimals.... but how it will know which is the right number of decimals because each field may have different decimals?
2) We should leave these fields as strings, to avoid all floating point stuff issues we are currently facing on

Please advise.

**Comment by htquach** [comment]
Answering the question in the original post:
Version should be stored as a string and not numeric value.
In addition, when store numeric 2 as float, it is acceptable to get back a 2.0 value. Also when storing a decimal value with long precision then the expected value to be returned would be truncated by the decimal accuracy set in the data persistent media.
This is not a valid bug as there is nothing wrong with how the values are being interpreted.
