### ISSUE TITLE
ORCM compute daemons sporadically incurs in a segmentation fault at startup

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#142]
After approximately 630 orcm launches (1 aggregator + 32 compute daemons) the following segmentation fault was observed in one of the compute daemons.

>node08: [node08:71535] *** Process received signal ***
node08: [node08:71535] Signal: Segmentation fault (11)
node08: [node08:71535] Signal code: Address not mapped (1)
node08: [node08:71535] Failing at address: (nil)
node08: [node08:71535] [ 0] /lib64/libpthread.so.0(+0xf890)[0x7fcb20e8d890]
node08: [node08:71535] [ 1] /opt/orcm-rc0/lib/liborcmopen-pal.so.0(opal_libevent2021_event_base_loop+0x13)[0x7fcb21a44c4e]
node08: [node08:71535] [ 2] /opt/orcm-rc0/lib/liborcm.so.0(+0x2b034)[0x7fcb21fed034]
node08: [node08:71535] [ 3] /lib64/libpthread.so.0(+0x80a4)[0x7fcb20e860a4]
node08: [node08:71535] [ 4] /lib64/libc.so.6(clone+0x6d)[0x7fcb20bbb7fd]
node08: [node08:71535] *** End of error message ***

Conditions: 
Uptime: aproximately 9 days
OS: SLES 12
Libraries: libodbc.so.2 not present in compute nodes (not required because compute daemons don't write to database)
Head node: statefull
Compute nodes: stateless

This one is most likely due to an issue with the OS of the node. However, ORCM should be capable of ending more gracefully.

Will keep monitoring!

**Comment by benmcclelland** [comment]
Due to the nature of these types of segfaults, we probably need the core file that should be generated along with it.  And we need to have access to the binary that was run (so if you are installing with rpm, just having access to the rpm is good too).

**Comment by forzaclaudio** [comment]
Closing this issue as the segmentation fault has not been observed after successfully launching 450,000 ORCM compute daemons .
