### ISSUE TITLE
ORCM logs negative values when asked to log only SIGAR component data

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#144]
When asking ORCM to only log SIGAR component into the database. The following metrics store negative values, e.g. -2 in the compute nodes

1. disk_ro_total
![node01orcmdb-sigardiskrototal](https://cloud.githubusercontent.com/assets/8369713/5844862/ecc1ab42-a17c-11e4-8c2c-1eb782eb342f.png)

2. disk_wo_total
![node01orcmdb-sigardiskwototal](https://cloud.githubusercontent.com/assets/8369713/5844868/fe6ad85a-a17c-11e4-8b91-0597d5a1b828.png)

3. disk_rb_total
![node01orcmdb-sigardiskrbtotal](https://cloud.githubusercontent.com/assets/8369713/5844875/07c0c4b4-a17d-11e4-9ac2-f3bff2fa9733.png)

4. disk_wb_total
![node01orcmdb-sigardiskwbtotal](https://cloud.githubusercontent.com/assets/8369713/5844882/17e6f1a6-a17d-11e4-8280-3c9e0accd981.png)

**Test environment:**

Feature | Value 
----------|----------
Uptime | aproximately 9 days 
OS | SLES 12 
DB | Postgresql 9.3-3.1.2 
Dependencies| libodbc.so.2 not present in compute nodes (not required because compute daemons don't write to database) 
Head node | 1 stateful
Compute nodes | 32 stateless

**Comment by vpedabal** [comment]
Can you turn up the verbosity to 10 and re-run this scan and send the output?

**Comment by forzaclaudio** [comment]
Ouput log from the aggregator nodes is:

>[headnode:193666] mca: base: components_register: registering db components
[headnode:193666] mca: base: components_register: found loaded component odbc
[headnode:193666] mca: base: components_register: component odbc register function successful
[headnode:193666] mca: base: components_register: found loaded component print
[headnode:193666] mca: base: components_register: component print register function successful
[headnode:193666] mca: base: components_open: opening db components
[headnode:193666] mca: base: components_open: found loaded component odbc
[headnode:193666] mca: base: components_open: found loaded component print
[headnode:193666] mca:db:select: checking available component odbc
[headnode:193666] mca:db:select: Querying component [odbc]
[headnode:193666] mca:db:select: checking available component print
[headnode:193666] mca:db:select: Querying component [print]
[headnode:193666] Final db priorities
[headnode:193666] 	Component: odbc Store Priority: 80
[headnode:193666] 	Component: print Store Priority: 5
[headnode:193666] mca: base: components_register: registering sensor components
[headnode:193666] mca: base: components_register: found loaded component heartbeat
[headnode:193666] mca: base: components_register: component heartbeat has no register or open function
[headnode:193666] mca: base: components_register: found loaded component sigar
[headnode:193666] mca: base: components_register: component sigar register function successful
[headnode:193666] mca: base: components_open: opening sensor components
[headnode:193666] mca: base: components_open: found loaded component heartbeat
[headnode:193666] mca: base: components_open: component heartbeat open function successful
[headnode:193666] mca: base: components_open: found loaded component sigar
[headnode:193666] mca: base: components_open: component sigar open function successful
[headnode:193666] sensor:base:select: Auto-selecting components
[headnode:193666] sensor:base:select Querying component [heartbeat]
[headnode:193666] sensor:base:select Query of component [heartbeat] set priority to 5
[headnode:193666] sensor:base:select Querying component [sigar]
[headnode:193666] sensor:base:select Query of component [sigar] set priority to 150
[headnode:193666] sensor:base:select Add module with priority [sigar] 150
[headnode:193666] sensor:base:select Add module with priority [heartbeat] 5
[headnode:193666] [[0,0],1] initializing heartbeat recvs
[headnode:193666] [[0,0],1] sensor:base: sensor start called
[headnode:193666] [[0,0],1] sensor:base: starting sensors
[headnode:193666] [[0,0],1] sensor:base: creating sampler with rate 5
[headnode:193666] sensor:base inventory collection not requested
[headnode:193666] 
******************************
Tue Jan 27 09:49:03 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[headnode:193666] db:odbc: Connection established to orcmdb_psql
[headnode:193666] db:odbc: Connection established to orcmdb_psql
[headnode:193666] [[0,0],1] sensor:base: sampling sensors
[headnode:193666] [[0,0],1] sensor:base: sampling component sigar
[headnode:193666] mem total: 67448094720 used: 2578661376 actual used: 1271812096 actual free: 66176282624
[headnode:193666] swap total: 2153771008 used: 489803776page_in: 12031 page_out: 130923
[headnode:193666] cpu user: 382307150 sys: 43737980 idle: 61965773130 wait: 59661150 nice: 50930 total: 62452172670
[headnode:193666] load_avg: 0.000000e+00 2.000000e-02 5.000000e-02
[headnode:193666] **FileSystem: / Reads: 73473** Writes: 2305502 ReadBytes: 2239484928 WriteBytes: 31295610880
[headnode:193666] FileSystem: / ReadsChange: 73473 WritesChange: 2305502 ReadBytesChange: 2239484928 WriteBytesChange: 31295610880
[headnode:193666] **FileSystem: /home Reads: 8476** Writes: 2030602 ReadBytes: 387207168 WriteBytes: 1024081018880
[headnode:193666] FileSystem: /home ReadsChange: 8476 WritesChange: 2030602 ReadBytesChange: 387207168 WriteBytesChange: 1024081018880
[headnode:193666] Totals: ReadsChange: 81949 WritesChange: 4336104 ReadBytesChange: 2626692096 WriteBytesChange: 1055376629760
[headnode:193666] Totals: ReadTime: 1296300 WriteTime: 1119173952 ioTime: 1120479784
[headnode:193666] Interface: lo RecvdPackets: 3597498 RecvdBytes: 1050814589 TransPackets: 3597498 TransBytes: 1050814589
[headnode:193666] Interface: lo RxPkts: 3597498 TxPkts: 3597498 RxBytes: 1050814589 TxBytes: 1050814589
[headnode:193666] Interface: eth0 RecvdPackets: 1028942458 RecvdBytes: 1026696819480 TransPackets: 1053802494 TransBytes: 213502096271
[headnode:193666] Interface: eth0 RxPkts: 1028942458 TxPkts: 1053802494 RxBytes: 1026696819480 TxBytes: 213502096271
[headnode:193666] Interface: eth0 RecvdPackets: 1028942458 RecvdBytes: 1026696819480 TransPackets: 1053802494 TransBytes: 213502096271
[headnode:193666] Interface: eth0 RxPkts: 1028942458 TxPkts: 1053802494 RxBytes: 1026696819480 TxBytes: 213502096271
[headnode:193666] Interface: eth1 RecvdPackets: 17069799 RecvdBytes: 2264897387 TransPackets: 1204590 TransBytes: 636452434
[headnode:193666] Interface: eth1 RxPkts: 17069799 TxPkts: 1204590 RxBytes: 2264897387 TxBytes: 636452434
[headnode:193666] Interface: eth2 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
[headnode:193666] Interface: eth2 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
[headnode:193666] Interface: eth3 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
[headnode:193666] Interface: eth3 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
[headnode:193666] Interface: ib0 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
[headnode:193666] Interface: ib0 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
[headnode:193666] Totals: RxPkts: 2078552213 TxPkts: 2112407076 RxBytes: 2056709350936 TxBytes: 428691459565
[headnode:193666] uptime: 1301353.720000
[headnode:193666] [[0,0],1] sensor:base: sampling component heartbeat
[headnode:193666] [[0,0],1] sending heartbeat
[headnode:193666] [[0,0],1] received beat from [[0,0],1]
[headnode:193666] [[0,0],1] received beat from [[0,0],2]
[headnode:193666] [[0,0],1] received beat from [[0,0],3]
[headnode:193666] [[0,0],1] sensor:base: sampling sensors
... same output approximately 23 times
[headnode:193666] [[0,0],1] sensor:base: sampling component heartbeat
[headnode:193666] [[0,0],1] sending heartbeat
[headnode:193666] [[0,0],1] received beat from [[0,0],1]
[headnode:193666] [[0,0],1] sensor:base: logging sensor sigar
[headnode:193666] [[0,0],1] Received log from host headnode
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded
[headnode:193666] [[0,0],1] received beat from [[0,0],2]
[headnode:193666] [[0,0],1] sensor:base: logging sensor sigar
[headnode:193666] [[0,0],1] Received log from host node01
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded
[headnode:193666] [[0,0],1] received beat from [[0,0],3]
[headnode:193666] [[0,0],1] sensor:base: logging sensor sigar
[headnode:193666] [[0,0],1] Received log from host node02
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded
[headnode:193666] odbc_store succeeded

As we can see from the highlighted data, data stored in the DB is of the order of 80000, as shown in Figure 1:
![headnodeorcmdb-sigardiskrototal](https://cloud.githubusercontent.com/assets/8369713/5926066/cdeaa2c2-a62d-11e4-9703-b127c6497755.png)
**Figure 1** Data stored in database for metric total disk read operations (SIGAR component). Data is of the order of 80000 ops

**Comment by forzaclaudio** [comment]
Ouput log from two compute nodes is:

>node01: [node01:236744] mca: base: component_find: unable to open /opt/orcm-rc0/lib/openmpi/mca_db_odbc: libodbc.so.2: cannot open shared object file: No such file or directory (ignored)
node02: [node02:153926] mca: base: component_find: unable to open /opt/orcm-rc0/lib/openmpi/mca_db_odbc: libodbc.so.2: cannot open shared object file: No such file or directory (ignored)
node01: [node01:236744] mca: base: components_register: registering sensor components
node01: [node01:236744] mca: base: components_register: found loaded component heartbeat
node01: [node01:236744] mca: base: components_register: component heartbeat has no register or open function
node01: [node01:236744] mca: base: components_register: found loaded component sigar
node01: [node01:236744] mca: base: components_register: component sigar register function successful
node01: [node01:236744] mca: base: components_open: opening sensor components
node01: [node01:236744] mca: base: components_open: found loaded component heartbeat
node01: [node01:236744] mca: base: components_open: component heartbeat open function successful
node01: [node01:236744] mca: base: components_open: found loaded component sigar
node01: [node01:236744] mca: base: components_open: component sigar open function successful
node01: [node01:236744] sensor:base:select: Auto-selecting components
node01: [node01:236744] sensor:base:select Querying component [heartbeat]
node01: [node01:236744] sensor:base:select Query of component [heartbeat] set priority to 5
node01: [node01:236744] sensor:base:select Querying component [sigar]
node01: [node01:236744] sensor:base:select Query of component [sigar] set priority to 150
node01: [node01:236744] sensor:base:select Add module with priority [sigar] 150
node01: [node01:236744] sensor:base:select Add module with priority [heartbeat] 5
node01: [node01:236744] [[0,0],2] initializing heartbeat recvs
node01: [node01:236744] [[0,0],2] sensor:base: sensor start called
node01: [node01:236744] [[0,0],2] sensor:base: starting sensors
node01: [node01:236744] [[0,0],2] sensor:base: creating sampler with rate 5
node01: [node01:236744] sensor:base inventory collection not requested
node02: [node02:153926] mca: base: components_register: registering sensor components
node02: [node02:153926] mca: base: components_register: found loaded component heartbeat
node02: [node02:153926] mca: base: components_register: component heartbeat has no register or open function
node02: [node02:153926] mca: base: components_register: found loaded component sigar
node02: [node02:153926] mca: base: components_register: component sigar register function successful
node02: [node02:153926] mca: base: components_open: opening sensor components
node02: [node02:153926] mca: base: components_open: found loaded component heartbeat
node02: [node02:153926] mca: base: components_open: component heartbeat open function successful
node02: [node02:153926] mca: base: components_open: found loaded component sigar
node02: [node02:153926] mca: base: components_open: component sigar open function successful
node02: [node02:153926] sensor:base:select: Auto-selecting components
node02: [node02:153926] sensor:base:select Querying component [heartbeat]
node02: [node02:153926] sensor:base:select Query of component [heartbeat] set priority to 5
node02: [node02:153926] sensor:base:select Querying component [sigar]
node02: [node02:153926] sensor:base:select Query of component [sigar] set priority to 150
node02: [node02:153926] sensor:base:select Add module with priority [sigar] 150
node02: [node02:153926] sensor:base:select Add module with priority [heartbeat] 5
node02: [node02:153926] [[0,0],3] initializing heartbeat recvs
node02: [node02:153926] [[0,0],3] sensor:base: sensor start called
node02: [node02:153926] [[0,0],3] sensor:base: starting sensors
node02: [node02:153926] [[0,0],3] sensor:base: creating sampler with rate 5
node02: [node02:153926] sensor:base inventory collection not requested
node01: [node01:236744] 
node01: ******************************
node01: Tue Jan 27 09:50:46 2015: ORCM version: 1.0.0a1 DAEMON: [[0,0],2] started and connected to AGGREGATOR: [[0,0],1]
node01: ******************************
node02: [node02:153926] 
node02: ******************************
node02: Tue Jan 27 09:50:45 2015: ORCM version: 1.0.0a1 DAEMON: [[0,0],3] started and connected to AGGREGATOR: [[0,0],1]
node02: ******************************
node01: [node01:236744] [[0,0],2] sensor:base: sampling sensors
node01: [node01:236744] [[0,0],2] sensor:base: sampling component sigar
node01: [node01:236744] mem total: 67586416640 used: 25227710464 actual used: 717008896 actual free: 66869407744
node01: [node01:236744] swap total: 0 used: 0page_in: 0 page_out: 0
node01: [node01:236744] cpu user: 110515020 sys: 4092620 idle: 26454860470 wait: 13156700 nice: 9510 total: 26583070610
node01: [node01:236744] load_avg: 0.000000e+00 1.000000e-02 5.000000e-02
node01: [node01:236744] **FileSystem: /opt Reads: 18446744073709551615** Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node01: [node01:236744] FileSystem: /opt ReadsChange: 18446744073709551615 WritesChange: 18446744073709551615 ReadBytesChange: 18446744073709551615 WriteBytesChange: 18446744073709551615
node01: [node01:236744] **FileSystem: /home Reads: 18446744073709551615** Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node01: [node01:236744] FileSystem: /home ReadsChange: 18446744073709551615 WritesChange: 18446744073709551615 ReadBytesChange: 18446744073709551615 WriteBytesChange: 18446744073709551615
node01: [node01:236744] Totals: ReadsChange: 18446744073709551614 WritesChange: 18446744073709551614 ReadBytesChange: 18446744073709551614 WriteBytesChange: 18446744073709551614
node01: [node01:236744] Totals: ReadTime: 18446744073709551614 WriteTime: 18446744073709551614 ioTime: 18446744073709551614
node01: [node01:236744] Interface: lo RecvdPackets: 41 RecvdBytes: 2836 TransPackets: 41 TransBytes: 2836
node01: [node01:236744] Interface: lo RxPkts: 41 TxPkts: 41 RxBytes: 2836 TxBytes: 2836
node01: [node01:236744] Interface: eth0 RecvdPackets: 32268961 RecvdBytes: 5933570142 TransPackets: 32524930 TransBytes: 32588918611
node01: [node01:236744] Interface: eth0 RxPkts: 32268961 TxPkts: 32524930 RxBytes: 5933570142 TxBytes: 32588918611
node01: [node01:236744] Interface: eth1 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth1 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Interface: eth2 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth2 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Interface: eth3 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth3 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Totals: RxPkts: 32269002 TxPkts: 32524971 RxBytes: 5933572978 TxBytes: 32588921447
node01: [node01:236744] uptime: 1107774.760000
node02: [node02:153926] [[0,0],3] sensor:base: sampling sensors
node02: [node02:153926] [[0,0],3] sensor:base: sampling component sigar
node02: [node02:153926] mem total: 67586416640 used: 25722912768 actual used: 717742080 actual free: 66868674560
node02: [node02:153926] swap total: 0 used: 0page_in: 0 page_out: 0
node02: [node02:153926] cpu user: 110314780 sys: 3478100 idle: 26456260750 wait: 13277520 nice: 4420 total: 26583738350
node02: [node02:153926] load_avg: 0.000000e+00 1.000000e-02 5.000000e-02
node02: [node02:153926] FileSystem: /opt Reads: 18446744073709551615 Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node02: [node02:153926] FileSystem: /opt ReadsChange: 18446744073709551615 WritesChange: 18446744073709551615 ReadBytesChange: 18446744073709551615 WriteBytesChange: 18446744073709551615
node02: [node02:153926] FileSystem: /home Reads: 18446744073709551615 Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node02: [node02:153926] FileSystem: /home ReadsChange: 18446744073709551615 WritesChange: 18446744073709551615 ReadBytesChange: 18446744073709551615 WriteBytesChange: 18446744073709551615
node02: [node02:153926] Totals: ReadsChange: 18446744073709551614 WritesChange: 18446744073709551614 ReadBytesChange: 18446744073709551614 WriteBytesChange: 18446744073709551614
node02: [node02:153926] Totals: ReadTime: 18446744073709551614 WriteTime: 18446744073709551614 ioTime: 18446744073709551614
node02: [node02:153926] Interface: lo RecvdPackets: 41 RecvdBytes: 2836 TransPackets: 41 TransBytes: 2836
node02: [node02:153926] Interface: lo RxPkts: 41 TxPkts: 41 RxBytes: 2836 TxBytes: 2836
node02: [node02:153926] Interface: eth0 RecvdPackets: 32382567 RecvdBytes: 6014555881 TransPackets: 32467116 TransBytes: 32582029788
node02: [node02:153926] Interface: eth0 RxPkts: 32382567 TxPkts: 32467116 RxBytes: 6014555881 TxBytes: 32582029788
node02: [node02:153926] Interface: eth1 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node02: [node02:153926] Interface: eth1 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node02: [node02:153926] Interface: eth2 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node02: [node02:153926] Interface: eth2 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node02: [node02:153926] Interface: eth3 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node02: [node02:153926] Interface: eth3 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node02: [node02:153926] Totals: RxPkts: 32382608 TxPkts: 32467157 RxBytes: 6014558717 TxBytes: 32582032624
node02: [node02:153926] uptime: 1107803.130000
node01: [node01:236744] [[0,0],2] sensor:base: sampling component heartbeat
node01: [node01:236744] [[0,0],2] sending heartbeat
node02: [node02:153926] [[0,0],3] sensor:base: sampling component heartbeat
node02: [node02:153926] [[0,0],3] sending heartbeat
node01: [node01:236744] [[0,0],2] sensor:base: sampling sensors
node01: [node01:236744] [[0,0],2] sensor:base: sampling component sigar
node01: [node01:236744] mem total: 67586416640 used: 25227087872 actual used: 716410880 actual free: 66870005760
node01: [node01:236744] swap total: 0 used: 0page_in: 0 page_out: 0
node01: [node01:236744] cpu user: 110515020 sys: 4092640 idle: 26454980550 wait: 13156710 nice: 9510 total: 26583190720
node01: [node01:236744] load_avg: 0.000000e+00 1.000000e-02 5.000000e-02
node01: [node01:236744] FileSystem: /opt Reads: 18446744073709551615 Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node01: [node01:236744] FileSystem: /opt ReadsChange: 0 WritesChange: 0 ReadBytesChange: 0 WriteBytesChange: 0
node01: [node01:236744] FileSystem: /home Reads: 18446744073709551615 Writes: 18446744073709551615 ReadBytes: 18446744073709551615 WriteBytes: 18446744073709551615
node01: [node01:236744] FileSystem: /home ReadsChange: 0 WritesChange: 0 ReadBytesChange: 0 WriteBytesChange: 0
node01: [node01:236744] Totals: ReadsChange: 0 WritesChange: 0 ReadBytesChange: 0 WriteBytesChange: 0
node01: [node01:236744] Totals: ReadTime: 18446744073709551614 WriteTime: 18446744073709551614 ioTime: 18446744073709551614
node01: [node01:236744] Interface: lo RecvdPackets: 41 RecvdBytes: 2836 TransPackets: 41 TransBytes: 2836
node01: [node01:236744] Interface: lo RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Interface: eth0 RecvdPackets: 32268979 RecvdBytes: 5933571746 TransPackets: 32524952 TransBytes: 32588923403
node01: [node01:236744] Interface: eth0 RxPkts: 18 TxPkts: 22 RxBytes: 1604 TxBytes: 4792
node01: [node01:236744] Interface: eth1 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth1 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Interface: eth2 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth2 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Interface: eth3 RecvdPackets: 0 RecvdBytes: 0 TransPackets: 0 TransBytes: 0
node01: [node01:236744] Interface: eth3 RxPkts: 0 TxPkts: 0 RxBytes: 0 TxBytes: 0
node01: [node01:236744] Totals: RxPkts: 18 TxPkts: 22 RxBytes: 1604 TxBytes: 4792
node01: [node01:236744] uptime: 1107779.760000
node02: [node02:153926] [[0,0],3] sensor:base: sampling sensors
... same output approximately 23 times
node01: [node01:236744] [[0,0],2] sending heartbeat
node02: [node02:153926] [[0,0],3] sensor:base: sampling component heartbeat
node02: [node02:153926] [[0,0],3] sending heartbeat
node02: --------------------------------------------------------------------------
node02: ORCM has detected failure of an orcm daemon:
node02: 
node02:   Failure time:     Tue Jan 27 09:52:44 2015
node02:   Reported from:    node02
node02:   Failed nodename:  [[0,0],1]
node02: 
node02: Messages have been rerouted - a restart of the failed
node02: daemon and/or node may be required.
node02: --------------------------------------------------------------------------
node02: [node02:153926] Tue Jan 27 09:52:44 2015: ORCM daemon [[0,0],3] shutting down with status 1 (SYS)
node01: --------------------------------------------------------------------------
node01: ORCM has detected failure of an orcm daemon:
node01: 
node01:   Failure time:     Tue Jan 27 09:52:45 2015
node01:   Reported from:    node01
node01:   Failed nodename:  [[0,0],1]
node01: 
node01: Messages have been rerouted - a restart of the failed
node01: daemon and/or node may be required.
node01: --------------------------------------------------------------------------
node01: [node01:236744] Tue Jan 27 09:52:45 2015: ORCM daemon [[0,0],2] shutting down with status 1 (SYS)
node02: [node02:153926] [[0,0],3] sensor:base: stopping sensors
node01: [node01:236744] [[0,0],2] sensor:base: stopping sensors
node01: [node01:236744] mca: base: close: component heartbeat closed
node01: [node01:236744] mca: base: close: unloading component heartbeat
node02: [node02:153926] mca: base: close: component heartbeat closed
node02: [node02:153926] mca: base: close: unloading component heartbeat
node01: [node01:236744] mca: base: close: component sigar closed
node01: [node01:236744] mca: base: close: unloading component sigar
node02: [node02:153926] mca: base: close: component sigar closed
node02: [node02:153926] mca: base: close: unloading component sigar

As we can see from the highlighted data, data stored in the DB is of the order of 80000, as shown in Figure 2:
![node01orcmdb-sigardiskrototal](https://cloud.githubusercontent.com/assets/8369713/5926469/ddd73166-a630-11e4-917b-7d977df4f21b.png)
Figure 2. Data stored in database for metric total disk read operations (SIGAR component). According to logs this should be on the order of  18,000 exa ops? (18,446,744,073,709,551,615)

**Comment by vpedabal** [comment]
I am not able to reproduce this issue in my desktop server and seems to be an issue on stateless nodes. At this point the workaround for this is not to sample disk stats on stateless machines. This can be achieved using the mca parameter 'sensor_sigar_disk=false"

Marking down this bug as release blocker. We'll mark this in the release notes.

**Comment by forzaclaudio** [comment]
Closing issue as workaround is valid. For future reference, if something is broken please refrain from using it and disable whenever possible.
