### ISSUE TITLE
ORCMD - Unregistered nodes in orcm-site.xml file drop a running ORCMD.

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#149]
If a node is not register in aggregator's orcm-site.xml file,  and a proper registered node is running (ORMCD launched), at the time the ORCMD in a not registered node is launched it is detected as valid (Issue #148), but the difference is that the registered node currently running ORCMD is dropped.

In spite of the root cause may be the same, this issue was opened independently to focus on ensuring ORCMD registered nodes are not dropped by unregistered nodes attempting to connect due to this is also another potential security issue.

**Comment by vpedabal** [comment]
For now, the suggestion is to use identical orcm-site.xml files. Future expectation is to catch/adapt to the changes.

**Comment by noahv** [comment]
Duplicate of #148
