### ISSUE TITLE
OCLI - ocli is not displaying supported subcommands in interactive mode

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#151]
when ocli is launched in interactive mode (that is, launching ocli without parameters), and the subcommand is typed, it is expected to display the valid parameters of the subcommand according documentation in this link:
<pre>
https://github.com/open-mpi/orcm/wiki/3.1.4-ocli
</pre>

CURRENT OUTPUT:
<pre>
[pedro@karate bin]$ ./ocli
*** WELCOME TO OCLI ***
Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
ocli> resource Unknown command: resource
[pedro@karate bin]$
</pre>

EXPECTED OUTPUT:
<pre>
% ocli
*** WELCOME TO OCLI ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
ocli> resource 
    status availability
ocli> resource
</pre>

**Comment by benmcclelland** [comment]
The documentation says that the tab key must be used to get possible command completions.  It seems like you might be typing enter instead of tab.  Can you paste in the part of the documentation that you believe is inaccurate in case I am just missing it?

**Comment by piniguez** [comment]
I apologize about this oversight. You are correct, the documentation says clearly users must press tab.

Closing this issue as invalid.
