### ISSUE TITLE
OCLT - oclt is not displaying supported subcommands in interactive mode

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#152]
when oclt is launched in interactive mode (that is, launching oclt without parameters), and the subcommand is typed, it is expected to display the valid parameters of the subcommand according documentation in this link:
<pre>
https://github.com/open-mpi/orcm/wiki/3.1.3-octl
</pre>

CURRENT OUTPUT:
<pre>
[pedro@karate bin]$ ./octl
*** WELCOME TO OCTL ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
   diag                 Diagnostics
   power                Power Budget
octl> resourceUnknown command: resource
[pedro@karate bin]$
</pre>

EXPECTED OUTPUT:
<pre>
% octl
*** WELCOME TO OCTL ***
 Possible commands:
   resource             Resource Information
   queue                Queue Information
   session              Session Management
   diag                 Diagnostics
   power                Power Budget
octl> resource 
    status add remove drain
octl> resource
</pre>

**Comment by benmcclelland** [comment]
see comments from issue #151

**Comment by piniguez** [comment]
I apologize about this oversight. You are correct, the documentation says clearly users must press tab.

Closing this issue as invalid.
