### ISSUE TITLE
ORCM Componentpower Plugin Requires MSR Module

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#157]
Wiki should mention the modprobe msr requirement.

**Comment by jjsong2** [comment]
Hi Noah, where should I add/edit wiki documents? Is it here?
  https://github.com/open-mpi/orcm/wiki/4-Developer-Guide

**Comment by vpedabal** [comment]
It's better to keep it somewhere here: https://github.com/open-mpi/orcm/wiki/2.1-ORCM-Build-and-Installation

**Comment by vpedabal** [comment]
Justin, can you update the pre-requisites here: https://github.com/open-mpi/orcm/wiki/2.1.08-Setting-Up-pre-requisites-for-RAS-Monitoring

And also update with nodepower and component power in this page: https://github.com/open-mpi/orcm/wiki/2.3-RAS-Monitoring

**Comment by jjsong2** [comment]
thank you Vineet. I have updated both links.
