### ISSUE TITLE
ORCM - Inventory Gathering - No inventory data is stored at all on database

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#158]
Inventory Data is not stored at all on the database. See following examples:

Important:
<pre>
      Notice there are no "odbc_store succeeded" messages at all for inventory gathering.
</pre>

Launching ORCMD for coretemp:
<pre>
[pedro@centospedro bin]$ sudo ./orcmd  -omca sensor heartbeat,coretemp --omca db_base_verbose 100 --omca db_odbc_dsn orcmdb_psql --omca db_odbc_user orcmuser:orc --omca db_odbc_table data_sample
[centospedro.zpn.intel.com:14153] mca: base: components_register: registering db components
[centospedro.zpn.intel.com:14153] mca: base: components_register: found loaded component odbc
[centospedro.zpn.intel.com:14153] mca: base: components_register: component odbc register function successful
[centospedro.zpn.intel.com:14153] mca: base: components_register: found loaded component print
[centospedro.zpn.intel.com:14153] mca: base: components_register: component print register function successful
[centospedro.zpn.intel.com:14153] mca: base: components_open: opening db components
[centospedro.zpn.intel.com:14153] mca: base: components_open: found loaded component odbc
[centospedro.zpn.intel.com:14153] mca: base: components_open: found loaded component print
[centospedro.zpn.intel.com:14153] mca:db:select: checking available component odbc
[centospedro.zpn.intel.com:14153] mca:db:select: Querying component [odbc]
[centospedro.zpn.intel.com:14153] mca:db:select: checking available component print
[centospedro.zpn.intel.com:14153] mca:db:select: Querying component [print]
[centospedro.zpn.intel.com:14153] Final db priorities
[centospedro.zpn.intel.com:14153]       Component: odbc Store Priority: 80
[centospedro.zpn.intel.com:14153]       Component: print Store Priority: 5
[centospedro.zpn.intel.com:14153] 
******************************
Mon Feb  2 06:06:33 2015: ORCM version: 0.7.0rc2 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[centospedro.zpn.intel.com:14153] db:odbc: Connection established to orcmdb_psql
[centospedro.zpn.intel.com:14153] db:odbc: Connection established to orcmdb_psql
[centospedro.zpn.intel.com:14153] odbc_store succeeded
[centospedro.zpn.intel.com:14153] odbc_store succeeded
[centospedro.zpn.intel.com:14153] odbc_store succeeded
^C[centospedro.zpn.intel.com:14153] Mon Feb  2 06:06:49 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interupted)
[centospedro.zpn.intel.com:14153] mca: base: close: unloading component odbc
[centospedro.zpn.intel.com:14153] mca: base: close: unloading component print
</pre>

Launching ORCMD for Inventory Data:
<pre>
[pedro@centospedro bin]$ sudo ./orcmd   -omca sensor dmidata,ipmi -omca sensor_base_collect_inventory true -omca sensor_base_collect_metrics false --omca db_base_verbose 100 --omca db_odbc
_dsn orcmdb_psql --omca db_odbc_user orcmuser:orc --omca db_odbc_table data_sample                                                                                                          
[centospedro.zpn.intel.com:14178] mca: base: components_register: registering db components
[centospedro.zpn.intel.com:14178] mca: base: components_register: found loaded component odbc
[centospedro.zpn.intel.com:14178] mca: base: components_register: component odbc register function successful
[centospedro.zpn.intel.com:14178] mca: base: components_register: found loaded component print
[centospedro.zpn.intel.com:14178] mca: base: components_register: component print register function successful
[centospedro.zpn.intel.com:14178] mca: base: components_open: opening db components
[centospedro.zpn.intel.com:14178] mca: base: components_open: found loaded component odbc
[centospedro.zpn.intel.com:14178] mca: base: components_open: found loaded component print
[centospedro.zpn.intel.com:14178] mca:db:select: checking available component odbc
[centospedro.zpn.intel.com:14178] mca:db:select: Querying component [odbc]
[centospedro.zpn.intel.com:14178] mca:db:select: checking available component print
[centospedro.zpn.intel.com:14178] mca:db:select: Querying component [print]
[centospedro.zpn.intel.com:14178] Final db priorities
[centospedro.zpn.intel.com:14178]       Component: odbc Store Priority: 80
[centospedro.zpn.intel.com:14178]       Component: print Store Priority: 5
[centospedro.zpn.intel.com:14178] FRU Read success!
[centospedro.zpn.intel.com:14178] Sensor 0: PS1 Power In
[centospedro.zpn.intel.com:14178] Sensor 1: PS1 Temperature
[centospedro.zpn.intel.com:14178] 
******************************
Mon Feb  2 06:07:38 2015: ORCM version: 0.7.0rc2 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[centospedro.zpn.intel.com:14178] db:odbc: Connection established to orcmdb_psql
[centospedro.zpn.intel.com:14178] db:odbc: Connection established to orcmdb_psql
 </pre>

**Comment by vpedabal** [comment]
Pedro, that is because we use db.store for storing the metric data, but use 'update_node_features' to store the inventory record. It probably is not printing out any log message. Did you verify if the database is still empty after running this, i.e. no new inventory records are getting updated?

**Comment by vpedabal** [comment]
@avilcheslopez : Does update_node_record print out any trace message?

**Comment by avilcheslopez** [comment]
The DB component does print a trace message upon successful completion (at a verbosity level of 2): "odbc update node features succeeded".

@piniguez: now, looking at the data, it seems like you've enabled sensor data gathering, because I only see the "odbc store succeeded" messages.

@vpedabal: is there a specific MCA parameter you have to pass to enable inventory gathering?

**Comment by vpedabal** [comment]
Yes there is, "-omca sensor_base_collect_inventory true" which @piniguez did enable.
Pedro can you also increase verbosity for inventory? "-omca sensor_base_verbose 10" and print out the output.

**Comment by vpedabal** [comment]
Just out of curiousity, does enabling print plugin work? Does the inventory information get logged onto screen?

**Comment by vpedabal** [comment]
I'm suspecting that the sensor framework is is attempting to store the inventory data even before the odbc component is initialized and the database handle is provided. There is a check for this, and since the check fails, the sensor framework doesn't store the data. 

This is a race condition issue that's been present from the beginning, but is visible more prominently after moving to opal progress thread engine. This kind of behaviour ''may'' be acceptable for metric data, where new data sets arrive with every sampling interval.

However inventory data gets logged only ''ONCE'' and if it misses that chance it will never get logged again. I'm trying to experiment with ways where the rest of the sensor's start functionality is performed ''only'' after the db is initialized and a db handle is provided. Will update if I find any results.

**Comment by piniguez** [comment]
Tested two alternatives solutions and both of them worked.
Will wait for fix to be integrated into official V07 branch and retest over there prior to close this issue
