### ISSUE TITLE
componentpower causes build to fail if ipmiutil is not installed

### ISSUE THREAD

**Issue by benmcclelland** [open-mpi/orcm#163]
The other plugins, ipmi and nodepower, successfully prevent building when ipmiutil is not installed, but componentpower seems to lack the check but still tries to include the ipmicmd.h which appears to come from ipmiutil packages.  The configure.m4 should be fixed to prevent building if ipmiutil is not installed.

configure output:
--- MCA component sensor:componentpower (m4 configuration macro)
checking for MCA component sensor:componentpower compile mode... dso
checking if MCA component sensor:componentpower can compile... yes

for the ones that work correctly:
--- MCA component sensor:ipmi (m4 configuration macro)
checking for MCA component sensor:ipmi compile mode... dso
checking for IPMI Sensor support... with_ipmi_sensor not specified!
IPMIUTIL Check failed and IPMI sensor not requested
IPMI Sensor not requested and dependency not met and ipmi sensor will not be built
checking if MCA component sensor:ipmi can compile... no

--- MCA component sensor:nodepower (m4 configuration macro)
checking for MCA component sensor:nodepower compile mode... dso
checking ipmicmd.h usability... no
checking ipmicmd.h presence... no
checking for ipmicmd.h... no
checking if MCA component sensor:nodepower can compile... yes

and the build error:
Making all in mca/sensor/componentpower
make[2]: Entering directory `/orcm/orcm/mca/sensor/componentpower'
CC       sensor_componentpower.lo
CC       sensor_componentpower_component.lo
sensor_componentpower.c:51:21: error: ipmicmd.h: No such file or directory

**Comment by jjsong2** [comment]
created a code review request. stakeholders please review it.

**Comment by jjsong2** [comment]
fixed it and pushed new code to master

**Comment by noahv** [comment]
Fix verfied:

configure:4465: --- MCA component sensor:componentpower (m4 configuration macro)
configure:202870: checking for MCA component sensor:componentpower compile mode
configure:202876: result: dso
configure:203405: checking if MCA component sensor:componentpower can compile
configure:203407: result: no
