### ISSUE TITLE
cfgi file20 component does not do validate the values supplied for a port

### ISSUE THREAD

**Issue by rmiesen** [open-mpi/orcm#167]
I was doing some testing of the new cfgi file20 component and was able to get the file20 component to return an ORCM_SUCCESS from a file containing port numbers that are out of the range of acceptable port numbers. Below is the configuration file I used to expose this bug:

```
<?xml version="2.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <scheduler>
    <description>Identify the node that houses the ORCM scheduler. Only
      one allowed at this time.</description>
    <node>
      <value>IRIS</value>
    </node>
    <port>
      <value>65536</value>
      <description>port value == 2^16</description>
    </port>
  </scheduler>
</configuration>
```

I can also expose this bug by passing in a port value of "-1".

**Comment by noahv** [comment]
Will not be fixed.  If file20 support is pursued this issue can be reopened.
