### ISSUE TITLE
cfgi file20 does not use the <?xml?> tag correctly

### ISSUE THREAD

**Issue by rmiesen** [open-mpi/orcm#168]
The current implementation of the file20 ORCM configuration language uses the <?xml?> tag to denote which version of the cfgi "language" to use. For example, `<?xml version='2.0'?>` is used by the current implementation of the file20 component to denote an xml file that conforms to the file 2.0 cfgi language. However, this usage of the <?xml?> tag violates the [W3C XML 1.0 standard's usage of the <?xml?> tag](http://www.w3.org/TR/2008/REC-xml-20081126/#NT-prolog).

A possible fix is to add a version attribute or tag to the file 2.0 standard, like so:
```
<?xml version='1.0'?>
<configuration>
  <version>
    <value>2.0</value>
  </version>
  <!-- ... -->
</configuration>
```

**Comment by rhc54** [comment]
Just a reminder: the cfgi 2.0 format is _not_ an XML format. It is simply a shorthand syntax that was convenient and _looks_ somewhat like XML. So violating the XML standard is irrelevant - it isn't XML, nor was it intended to be.
