### ISSUE TITLE
cfgi file20 component permits assigning a core with an invalid value

### ISSUE THREAD

**Issue by rmiesen** [open-mpi/orcm#170]
I was doing some unit testing of the cfgi file20 component and I was able to get the file20 component to gleefully accept a core with a negative value, even though this doesn't make any sense:

```
<?xml version="2.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <cluster>
    <value>PENTIUM</value>
    <row>
      <value>ROW1</value>
      <cores>
        <value>-1</value>
      </cores>
      <controller>
        <value>ATOM001</value>
        <aggregator>
          <value>y</value>
        </aggregator>
        <port>
          <value>55815</value>
        </port>
      </controller>
    </row>
  </cluster>
</configuration>
```

The same results occur when I supply no value to the cores element---either via an empty value "<value></value>" or by omitting the value tag altogether.

**Comment by noahv** [comment]
Will not be fixed.  If file20 support is pursued this issue can be reopened.
