### ISSUE TITLE
ORCMD- componentpower:  unaccurate data when MSR driver is missing

### ISSUE THREAD

**Issue by RafaARV** [open-mpi/orcm#177]
Version: 1.0.0a1
Commit: 07f0ec2e4f4c435dec8426d5e4e5851ef746b883
OS: CentOS 7  Kernel - 3.10.0-229.1.2.el7.x86_64

Orcmd fails to give accurate values when the msr driver is missing on the system instead of returning an error.

>[root@xxxxxx]# ./orcmd -omca sensor heartbeat,componentpower
[xxxxxxxxx:29202] 
******************************
Wed May 13 14:23:35 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: store; data:
primary_key=componentpower,ctime=2015-05-13 14:23:45.812-0500,hostname=xxxxxx,**cpu0_power=1000.000000:W,cpu1_power=1000.000000:W,ddr0_power=54543124.000000:W,ddr1_power=54543124.000000:W**
[xxxxxx:29202] Wed May 13 14:24:36 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interrupted)
[root@xxxxxx bin]# modprobe msr
[root@xxxxxx bin]# lsmod |grep msr

**Comment by jjsong2** [comment]
fix: if /dev/cpu/X/msr does not exist, init() will return ORTE_ERROR

**Comment by RafaARV** [comment]
Still not working.

Version: 1.0.0a1
Commit e03c63dcb843c7260d13c67f33a20334cee3595f
Author: jjsong <jjsong@epp-hpc-h3-00.(none)>
Date:   Wed Jun 10 09:04:15 2015 -0700
OS: CentOS 7 kernel - 3.10.0-229.4.2.el7.x86_64

>
[root@xxxxxxxx bin]#  ./orcmd -omca sensor heartbeat,componentpower
[xxxxxxx.intel.com:10828] 
******************************
Wed Jun 10 15:19:14 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: store; data:
primary_key=componentpower,ctime=2015-06-10 15:19:24.558-0500,hostname=xxxxx,**cpu0_power=1000.000000:W,cpu1_power=1000.000000:W,ddr0_power=1270.099487:W,ddr1_power=1270.099487:W**
[xxxxxx.intel.com:10828] Wed Jun 10 15:19:34 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interrupted)
>


The msr files /dev/cpu/X/msr exists:
>
[root@xxxxxxxx bin]# ls /dev/cpu/0/
cpuid  msr
>


But the module is the one that is missing (there is no msr.ko)
```
[root@xxxxxxx 0]# ls -R /lib/modules/`uname -r`/kernel/ | grep msr
arcmsr
/lib/modules/3.10.0-229.4.2.el7.x86_64/kernel/drivers/scsi/arcmsr:
arcmsr.ko
```

**Comment by jjsong2** [comment]
Do other arch MSRs reads (e.g. 0x1a0, 0x198, ...) return correct values?

Since the msr.ko should be loaded on such OS, I suggest we amend the wiki page and add one note "please load needed modules and verify /dev/cpu/X/msr works properly".

**Comment by RafaARV** [comment]
Took me a while to figure this out but seems like msr module is in fact compiled, just that it's compiled directly in the kernel and not as loadable module:
>
[root@xxxxxx Downloads]# cat /boot/config-3.10.0-229.4.2.el7.x86_64 | grep MSR
CONFIG_X86_DEBUGCTLMSR=y
**CONFIG_X86_MSR=y**
CONFIG_SCSI_ARCMSR=m
>

Seems like some msr reads return correct values, but I'm not sure that all values are correct:
>
[root@xxxxx Downloads]# rdmsr  0x1ac --bitfield 14:0 --decimal
1040
[root@xxxxx Downloads]# rdmsr  0x1ac --bitfield 30:16 --decimal
880
[root@xxxxx Downloads]# rdmsr  0x1a0
850089
[root@xxxxx rafa]# rdmsr -a 0x198
c
c
c
c
c
c
c
c
c
c
c
c
>

0x1ac --- 130W 110amps
0x1a0 --- Turbo enabled
0x198 --- Don't really know how to format this data. But as far as I know it is the voltage.

**Comment by RafaARV** [comment]
After searching for the power related registers, found that the following registers doesn´t seems to exist for Gulftown/Westmere architecture (I've a Xeon X5680):
> 
0x606 MSR_RAPL_POWER_UNIT
0x611 MSR_PKG_ENERGY_STATUS
0x619 MSR_DRAM_ENERGY_STATUS
>

The results of the rdmsr command are:
>
[root@xxxxx rafa]# rdmsr -a 0x606
rdmsr: CPU 0 cannot read MSR 0x00000606
[root@xxxxx rafa]# rdmsr -a 0x611
rdmsr: CPU 0 cannot read MSR 0x00000611
[root@xxxxxx rafa]# rdmsr -a 0x619
rdmsr: CPU 0 cannot read MSR 0x00000619
>

Architecture must be validated and if it is not fully supported, at least, a warning is required.

**Comment by jjsong2** [comment]
I will add more check codes in init(). I am using the latest orcm. However, this version of orcm (I haven't changed anything) cannot be built. the error is shown below. Who can help? Thanks.

===================
  CCLD     liborcmopen-pal.la
make[2]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal'
Making all in tools/wrappers
make[2]: Entering directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal/tools/wrappers'
  SED      generic_wrapper.1
  CC       opal_wrapper.o
  SED      opal_wrapper.1
rm -f opalcc.1
rm -f opalc++.1
sed -e 's/#COMMAND#/opalcc/g' -e 's/#PROJECT#/Open PAL/g' -e 's/#PROJECT_SHORT#/OPAL/g' -e 's/#LANGUAGE#/C/g' < ../../../opal/tools/wrappers/generic_wrapper.1 > opalcc.1
sed -e 's/#COMMAND#/opalc++/g' -e 's/#PROJECT#/Open PAL/g' -e 's/#PROJECT_SHORT#/OPAL/g' -e 's/#LANGUAGE#/C++/g' < ../../../opal/tools/wrappers/generic_wrapper.1 > opalc++.1
  CCLD     opal_wrapper
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_create_event'
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_enqueue_event'
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_open'
collect2: ld returned 1 exit status
make[2]: *** [opal_wrapper] Error 1
make[2]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal/tools/wrappers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal'
make: *** [all-recursive] Error 1

**Comment by rhc54** [comment]
It appears you are trying to build psm support under libfabric for some reason, but aren't correctly linking the required files

**Comment by jjsong2** [comment]
moved MSRs check from start() to init()

added return data content check in log()

master branch commit id: 34c2718be232ff2b91429683dd0883ee410ea48b

**Comment by RafaARV** [comment]
It works. Now it shows the errors as it should:
>
[root@xxxx bin]# ./orcmd -omca sensor heartbeat,componentpower
**[xxxxx:15581] ERROR: reading msr file**
[xxxxx:15581] 
******************************
Wed Jun 17 17:59:07 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: store; data:
primary_key=componentpower,ctime=2015-06-17 17:59:17.444-0500,hostname=xxxx,cpu0_power=-1.000000:W,cpu1_power=-1.000000:W,ddr0_power=inf:W,ddr1_power=inf:W
**[xxxx:15581] componentpower sensor data not logged due to unexpected return value from RAPL**
**[xxxx:15581] componentpower sensor data not logged due to unexpected return value from RAPL**
**[xxxx:15581] componentpower sensor data not logged due to unexpected return value from RAPL**
**[xxxx:15581] componentpower sensor data not logged due to unexpected return value from RAPL**
**[xxxx:15581] componentpower sensor data not logged due to unexpected return value from RAPL**
[xxxx:15581] Wed Jun 17 17:59:37 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interrupted)
>

This issue can be closed now. Thank you Justin.

**Comment by forzaclaudio** [comment]
Out of curiosity, what happens with the fix when using either Odbc or Postgres plugin? It looks to me that this was only tested with the print component.

**Comment by RafaARV** [comment]
You are right David,

With the DB enabled it is logging incorrect values, it should not log this incorrect values. Also there are some suspicious warnings.
>
[root@xxxx rafa]# /opt/orcm_test/bin/orcmd -omca sensor heartbeat,componentpower -omca db_postgres_uri localhost:5432 -omca db_postgres_database orcmdb -omca db_postgres_user orcmuser:orcmpassword --omca db_base_verbose 100
[xxxx:06501] mca: base: components_register: registering framework db components
[xxxx:06501] mca: base: components_register: found loaded component print
[xxxx:06501] mca: base: components_register: component print register function successful
[xxxx:06501] mca: base: components_register: found loaded component odbc
[xxxx:06501] mca: base: components_register: component odbc register function successful
[xxxx:06501] mca: base: components_register: found loaded component postgres
[xxxx:06501] mca: base: components_register: component postgres register function successful
[xxxx:06501] mca: base: components_open: opening db components
[xxxx:06501] mca: base: components_open: found loaded component print
[xxxx:06501] mca: base: components_open: found loaded component odbc
[xxxx:6501] mca: base: components_open: found loaded component postgres
[xxxx:06501] mca:db:select: checking available component print
[xxxx:06501] mca:db:select: Querying component [print]
[xxxx:06501] mca:db:select: checking available component odbc
[xxxx:06501] mca:db:select: Querying component [odbc]
[xxxx:06501] mca:db:select: checking available component postgres
[xxxx:06501] mca:db:select: Querying component [postgres]
[xxxx:06501] Final db priorities
[xxxx:06501] 	Component: postgres Store Priority: 15
[xxxx:06501] 	Component: odbc Store Priority: 10
[xxxx:06501] 	Component: print Store Priority: 5
[xxxx:06501] db:postgres: Connection established to orcmdb
[xxxx:06501] 
******************************
Thu Jun 18 11:10:48 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
[xxxx:06501] db:postgres: Connection established to orcmdb
**WARNING:  there is no transaction in progress**
**[xxxx:06501] postgres_store_sample succeeded**
**WARNING:  there is no transaction in progress**
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
[xxxx:06501] Thu Jun 18 11:11:21 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interrupted)
[xxxx:06501] mca: base: close: unloading component print
[xxxx:06501] mca: base: close: unloading component odbc
[xxxx:06501] mca: base: close: unloading component postgres
>


The incorrect data that was stored was:
>
orcmdb=# SELECT * FROM data_sample_raw WHERE time_stamp BETWEEN '2015-06-18 01:00:00' AND '2015-06-18 20:00:00';
    hostname     |         data_item         |         time_stamp         | value_int | value_real | value_str | units | data_type_id |       time_stamp_db        |  id   
-----------------+---------------------------+----------------------------+-----------+------------+-----------+-------+--------------+----------------------------+-------
 xxxx | componentpower_cpu0_power | 2015-06-18 11:08:55.343166 |           | **147.102798** |           | W     |           16 | 2015-06-18 11:08:55.343984 | 34008
 xxxx | componentpower_cpu1_power | 2015-06-18 11:08:55.343166 |           | **147.102798** |           | W     |           16 | 2015-06-18 11:08:55.343984 | 34009
 xxxx | componentpower_ddr0_power | 2015-06-18 11:08:55.343166 |           | **147.102798** |           | W     |           16 | 2015-06-18 11:08:55.343984 | 34010
 xxxx | componentpower_ddr1_power | 2015-06-18 11:08:55.343166 |           | **147.102798** |           | W     |           16 | 2015-06-18 11:08:55.343984 | 34011
 xxxx | componentpower_cpu0_power | 2015-06-18 11:10:58.1126   |           |       **1000** |           | W     |           16 | 2015-06-18 11:10:58.114113 | 34012
 xxxx | componentpower_cpu1_power | 2015-06-18 11:10:58.1126   |           |       **1000** |           | W     |           16 | 2015-06-18 11:10:58.114113 | 34013
 xxxx | componentpower_ddr0_power | 2015-06-18 11:10:58.1126   |           |  **98472112** |           | W     |           16 | 2015-06-18 11:10:58.114113 | 34014
 xxxx | componentpower_ddr1_power | 2015-06-18 11:10:58.1126   |           |   **98472112** |           | W     |           16 | 2015-06-18 11:10:58.114113 | 34015
(8 rows)
>

**Comment by RafaARV** [comment]
Sorry I got confused by the several versions I have in my computer. The newest one works as it should, it is not logging incorrect data to the database. Sorry Justin, your fix is right.

>
[root@xxxx opt]# /opt/orcm_test_msr/bin/orcmd -omca sensor heartbeat,componentpower -omca db_postgres_uri localhost:5432 -omca db_postgres_database orcmdb -omca db_postgres_user orcmuser:orcmpassword
[xxxx:09275] ERROR: reading msr file
[xxxx:09275] 
******************************
Thu Jun 18 12:40:24 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
WARNING:  there is no transaction in progress
[xxxx:09275] ***********************************************
[xxxx:09275] db:postgres: Unable to record data sample: 
[xxxx:09275] ERROR:  column "inf" does not exist
LINE 1: ...wer_ddr0_power','2015-06-18 12:40:34.313620',NULL,inf,NULL,'...
                                                             ^
[xxxx:09275] ***********************************************
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
[xxxx:09275] Thu Jun 18 12:41:31 2015: ORCM aggregator [[0,0],1] shutting down with status -9 (Interrupted)
>

Database query:
>
orcmdb=# SELECT * FROM data_sample_raw WHERE time_stamp BETWEEN '2015-06-18 12:00:00' AND '2015-06-18 20:00:00';
 hostname | data_item | time_stamp | value_int | value_real | value_str | units | data_type_id | time_stamp_db | id 
----------+-----------+------------+-----------+------------+-----------+-------+--------------+---------------+----
(0 rows)
>

**Comment by noahv** [comment]
Fix verified by Rafa.
