### ISSUE TITLE
orcm build fails

### ISSUE THREAD

**Issue by jjsong2** [open-mpi/orcm#178]
orcm build fails with error shown below:

../../opal/runtime/opal_init.c:72:2: warning: #ident is a GCC extension
  CCLD     liborcmopen-pal.la
make[2]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal'
Making all in tools/wrappers
make[2]: Entering directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal/tools/wrappers'
  SED      generic_wrapper.1
  CC       opal_wrapper.o
  SED      opal_wrapper.1
rm -f opalcc.1
rm -f opalc++.1
sed -e 's/#COMMAND#/opalcc/g' -e 's/#PROJECT#/Open PAL/g' -e 's/#PROJECT_SHORT#/OPAL/g' -e 's/#LANGUAGE#/C/g' < ../../../opal/tools/wrappers/generic_wrapper.1 > opalcc.1
sed -e 's/#COMMAND#/opalc++/g' -e 's/#PROJECT#/Open PAL/g' -e 's/#PROJECT_SHORT#/OPAL/g' -e 's/#LANGUAGE#/C++/g' < ../../../opal/tools/wrappers/generic_wrapper.1 > opalc++.1
  CCLD     opal_wrapper
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_create_event'
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_enqueue_event'
../../../opal/.libs/liborcmopen-pal.so: undefined reference to `psmx_eq_open'
collect2: ld returned 1 exit status
make[2]: *** [opal_wrapper] Error 1
make[2]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal/tools/wrappers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/disk1/jjsong/proj/orcm_issue177_061015/mybuild/opal'
make: *** [all-recursive] Error 1

**Comment by noahv** [comment]
Does not reproduce.   -- Noah
