### ISSUE TITLE
ORCM v0.9 Branch Missing Official 0.9.0 Version String

### ISSUE THREAD

**Issue by hkbai** [open-mpi/orcm#179]
<b><i>[reporter="noah", created="Mon, 29 Jun 2015 21:55:33 +0000"]</i></b>
<p>Description of problem: </p>

<p>Orcmd version string does not match the v0.9 version string from the release target RPM.  The release RPM source must have <br/>
been modified but not committed and pushed?</p>

<p>Version-Release number of selected component (if applicable): </p>

<p> openrcm-0.9.0a1-1</p>

<p>Steps to Reproduce:</p>

<p>git clone  https://github.com/open-mpi/orcm<br/>
cd orcm; git checkout v0.9<br/>
./autogen.pl; ./configure --prefix=/opt/openrcm_test; make -j2<br/>
sudo make install<br/>
/opt/openrcm_test/bin/orcmd -V</p>

<p>Actual results:</p>

<p><span class="error">&#91;Mon Jun 29 17:49:00 noah@centos7:orcm&#93;</span> <span class="error">&#91;v0.9&#93;</span> /opt/openrcm_test/bin/orcmd -V<br/>
orcmd 0.9.0a1</p>

<p>Report bugs to <a href="https://github.com/open-mpi/orcm/issues" class="external-link" rel="nofollow">https://github.com/open-mpi/orcm/issues</a></p>

<p>Expected results: </p>

<p><span class="error">&#91;Mon Jun 29 14:51:32 noah@master3:openrcm-0.9.0&#93;</span> pwd<br/>
/home/noah/rpm/BUILD/openrcm-0.9.0<br/>
<span class="error">&#91;Mon Jun 29 14:51:33 noah@master3:openrcm-0.9.0&#93;</span> /opt/openrcm/bin/orcmd -V<br/>
orcmd 0.9.0</p>

<p>Report bugs to <a href="https://github.com/open-mpi/orcm/issues" class="external-link" rel="nofollow">https://github.com/open-mpi/orcm/issues</a></p>

<p>Additional info:</p>

<p>VERSION file needs updates in the v0.9 branch to fix this.</p>

**Comment by noahv** [comment]
Will not be fixed.  Later versions avoided this.  -- Noah
