### ISSUE TITLE
Nodepower reports suspicious values on the aggregator node #75

### ISSUE THREAD

**Issue by hkbai** [open-mpi/orcm#180]
<b><i>[reporter="habaraja", created="Tue, 23 Jun 2015 16:52:55 +0000"]</i></b>
<p>OCRM Nodepower has power consumptions drops at different period of time samples.</p>

**Comment by hkbai** [comment]
<b><i>[author="habaraja", created="Tue, 23 Jun 2015 16:59:52 +0000"]</i></b>
<p>The issue is not resolve yet. The test execution were run with latest from ORCM v0.9, at 12 nodes during 3 hrs. All nodes are showing and average of 6 drops per node. The following is a reading sample from the DB, it is reading an average of 341 watts and suddently it falls to 160 and go back to 342.</p>

<p>9099	342.72000100000002<br/>
9104	342.81332400000002<br/>
9109	342.78735399999999<br/>
9114	342.94665500000002<br/>
9119	342.866669<br/>
9124	160.933334<br/>
9129	342.82666<br/>
9134	343.07998700000002<br/>
9139	342.866669<br/>
9144	342.79998799999998</p>

**Comment by hkbai** [comment]
<b><i>[author="habaraja", created="Thu, 2 Jul 2015 04:13:10 +0000"]</i></b>
<p>The power reads drops are due the accumulator variables overflow on the call_readein function from the ipmi_cmdraw, the accumulator is returned by the cmdraw call compose by 3 unsigned bytes, they are getting some bit handling, it’s like searching a sign bit and moving it to the msb and finally seems like the data read is converted from unsigned to signed and the range of it is from -8,388,608 to 8,388,607.</p>

<p>temp_value<span class="error">&#91;0&#93;</span>=responseData<span class="error">&#91;1&#93;</span>;<br/>
temp_value<span class="error">&#91;1&#93;</span>=responseData<span class="error">&#91;2&#93;</span>;<br/>
temp_value<span class="error">&#91;1&#93;</span>&=0x7f;<br/>
temp_value<span class="error">&#91;2&#93;</span>=responseData<span class="error">&#91;3&#93;</span>;<br/>
if (temp_value<span class="error">&#91;2&#93;</span>&0x1)</p>
{
    temp_value[1]|=0x80;
}

<p>The overflow always happens when the accumulator goes above 8,388,607. So the collect_sample function has the cmdraw value and detects the overflow, and apparently seems to handle it, but this might not be working due the value calculate it goes above 1000 watts and the following code protection set the current power PA to -1, so this return value plus the power PB value ~160, it’s the drop value shown by the picture previously attached.  The overflow and the same situation also happens to the accumulator B, therefore the power drops looks in pairs at certain periods. </p>

<p>    node_power.power_a.cur=(double)val1/(double)val2;<br/>
    if (node_power.power_a.cur>1000.0)</p>
{
node_power.power_a.cur=-1.0;
    }

<p>The following it’s an execution example of the mentioned above the last correct value return by the orcm, the overflow of accumulator a, and then the logic and the drop of the power. </p>

<p><span class="error">&#91;master4:189321&#93;</span> ret=0, respData<span class="error">&#91;len=7&#93;</span>:<br/>
<span class="error">&#91;master4:189321&#93;</span> 06<br/>
<span class="error">&#91;master4:189321&#93;</span> cb<br/>
<span class="error">&#91;master4:189321&#93;</span> 7b<br/>
<span class="error">&#91;master4:189321&#93;</span> 16<br/>
<span class="error">&#91;master4:189321&#93;</span> 43<br/>
<span class="error">&#91;master4:189321&#93;</span> a5<br/>
<span class="error">&#91;master4:189321&#93;</span> ab<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> Processing Readein<br/>
<span class="error">&#91;master4:189321&#93;</span> ret_val<span class="error">&#91;0&#93;</span>=752587, ret_val<span class="error">&#91;1&#93;</span>=11248963<br/>
<span class="error">&#91;master4:189321&#93;</span> A.Accu = 752587 A.Cnt = 11248963<br/>
<span class="error">&#91;master4:189321&#93;</span> a_accu_curr - a_accu_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> a_cnt_curr - a_cnt_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> Final A.power: 161.826667 watts<br/>
<span class="error">&#91;master4:189321&#93;</span> ret=0, respData<span class="error">&#91;len=7&#93;</span>:<br/>
<span class="error">&#91;master4:189321&#93;</span> 06<br/>
<span class="error">&#91;master4:189321&#93;</span> 04<br/>
<span class="error">&#91;master4:189321&#93;</span> 53<br/>
<span class="error">&#91;master4:189321&#93;</span> ff<br/>
<span class="error">&#91;master4:189321&#93;</span> 81<br/>
<span class="error">&#91;master4:189321&#93;</span> a3<br/>
<span class="error">&#91;master4:189321&#93;</span> ab<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> Processing Readein<br/>
<span class="error">&#91;master4:189321&#93;</span> ret_val<span class="error">&#91;0&#93;</span>=8377092, ret_val<span class="error">&#91;1&#93;</span>=11248513<br/>
<span class="error">&#91;master4:189321&#93;</span> B.Accu = 8377092 B.Cnt = 11248513<br/>
<span class="error">&#91;master4:189321&#93;</span> b_accu_curr - b_accu_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> b_cnt_curr - b_cnt_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> Final B.power: 181.893333 watts<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> FINAL A+B POWER: 343.720000 watts<br/>
DB request: store; data:<br/>
primary_key=nodepower,ctime=2015-06-30 22:12:48.163-0700,hostname=master4,nodepower=343.720001:W<br/>
<span class="error">&#91;master4:189321&#93;</span> ret=0, respData<span class="error">&#91;len=7&#93;</span>:<br/>
<span class="error">&#91;master4:189321&#93;</span> 06<br/>
<span class="error">&#91;master4:189321&#93;</span> 3d<br/>
<span class="error">&#91;master4:189321&#93;</span> 2b<br/>
<span class="error">&#91;master4:189321&#93;</span> 17<br/>
<span class="error">&#91;master4:189321&#93;</span> 8e<br/>
<span class="error">&#91;master4:189321&#93;</span> a5<br/>
<span class="error">&#91;master4:189321&#93;</span> ab<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> Processing Readein<br/>
<span class="error">&#91;master4:189321&#93;</span> ret_val<span class="error">&#91;0&#93;</span>=764733, ret_val<span class="error">&#91;1&#93;</span>=11249038<br/>
<span class="error">&#91;master4:189321&#93;</span> A.Accu = 764733 A.Cnt = 11249038<br/>
<span class="error">&#91;master4:189321&#93;</span> a_accu_curr - a_accu_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> a_cnt_curr - a_cnt_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> Final A.power: 161.946667 watts<br/>
<span class="error">&#91;master4:189321&#93;</span> ret=0, respData<span class="error">&#91;len=7&#93;</span>:<br/>
<span class="error">&#91;master4:189321&#93;</span> 06<br/>
<span class="error">&#91;master4:189321&#93;</span> 52<br/>
<span class="error">&#91;master4:189321&#93;</span> 08<br/>
<span class="error">&#91;master4:189321&#93;</span> 00<br/>
<span class="error">&#91;master4:189321&#93;</span> cc<br/>
<span class="error">&#91;master4:189321&#93;</span> a3<br/>
<span class="error">&#91;master4:189321&#93;</span> ab<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> Processing Readein<br/>
<span class="error">&#91;master4:189321&#93;</span> ret_val<span class="error">&#91;0&#93;</span>=2130, ret_val<span class="error">&#91;1&#93;</span>=11248588<br/>
<span class="error">&#91;master4:189321&#93;</span> B.Accu = 2130 B.Cnt = 11248588<br/>
<span class="error">&#91;master4:189321&#93;</span> b_accu_curr + 32768 - b_cnt_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> b_cnt_curr - b_cnt_prev<br/>
<span class="error">&#91;master4:189321&#93;</span> Final B.power: -1.000000 watts<br/>
<span class="error">&#91;master4:189321&#93;</span><br/>
<span class="error">&#91;master4:189321&#93;</span> FINAL A+B POWER: 160.946667 watts<br/>
DB request: store; data:<br/>
primary_key=nodepower,ctime=2015-06-30 22:12:53.169-0700,hostname=master4,nodepower=160.946671:W</p>

<p>These are my thoughts right now, I’m still trying to understand the mechanism of it, in the mid time I hope this information helps and also I’m looking for any corrections or comments about it. </p>

<p>Thanks</p>

**Comment by hkbai** [comment]
<b><i>[author="jjsong", created="Thu, 2 Jul 2015 20:46:49 +0000"]</i></b>
<p>thank you for providing the trace. my experiment platforms have been down due to lab move. I'll follow up early next week.</p>

**Comment by hkbai** [comment]
<b><i>[author="habaraja", created="Mon, 6 Jul 2015 17:15:24 +0000"]</i></b>
<p>I made a couple of experiments, the first was to run the orcmd on the same node as the ipmitool and red the nodepower at the same sample rate, the result of it is that impitool has a better handling of the data and it is not showing the power drops, please find attached a small  chart with the results. </p>

<p>Therefore I did some experiments and modified the overflow handling and so far no power drops, please find attached the patch. </p>

**Comment by hkbai** [comment]
<b><i>[author="jjsong", created="Mon, 6 Jul 2015 18:14:01 +0000"]</i></b>
<p>Thanks for providing more information. Our servers are still down due to lab move. Based on the data, overflow processing should be changed a bit. Is there a machine that I can borrow (coding, compiling, testing)?</p>

**Comment by hkbai** [comment]
<b><i>[author="habaraja", created="Mon, 6 Jul 2015 22:57:55 +0000"]</i></b>
<p>The attached fix was tested on a 12 nodes running a Linkpack, during 1/3 of the test initial execution time, the remaining time, nodes ran without workload. Please find attached the test result (tomate chart) showing successful results.</p>

<p>Issue is reproducible on mercury, I’m using master4, do you have access to it?</p>

**Comment by hkbai** [comment]
<b><i>[author="jjsong", created="Mon, 6 Jul 2015 23:14:27 +0000"]</i></b>
<p>Thanks for providing the patch. Seems overflow is marked as an error. I am OK with the fix. If you would like me to try it or have more fixes, could you please send me detailed instructions how to use "master4"? thanks.</p>

**Comment by noahv** [comment]
Fixed by the following:

commit b97278dbb72dfe81d9446a8c2273885f5be7c0d2
Author: Hector Barajas <hector.a.barajas.villalobos@intel.com>
Date:   Wed Jul 15 15:53:41 2015 -0400
 
    Bugfix: Nodepower reports suspicious values on the aggregator node#75
