### ISSUE TITLE
SIGAR or Postgres plugin consume too much memory and possibly leaking it at a high rate

### ISSUE THREAD

**Issue by hkbai** [open-mpi/orcm#181]
<b><i>[reporter="dclaudio", created="Tue, 16 Jun 2015 19:15:49 +0000", resolved="Mon, 29 Jun 2015 16:18:59 +0000"]</i></b>
<p>When running ORCM with SIGAR plugin enabled. Memory in the AG, which is also running the DB, is depleting at rate of about 0.77 GB/hr. Process memory-related metrics show that memory usage is increasing monotonically during the run and process memory usage correlates well with mem_used, mem_actual_free and mem_actual_used. This rate implies that a system with 62 GB of RAM will run out of memory in 3.5 days (81 hours) This behavior is reproducible for the cases when CORETEMP and FREQ are running in their own threads. Test conditions were:</p>

<p>Master4 subcluster in Mercury: 1 AG + 12 CN<br/>
S.O. SLES 12<br/>
Sampling Rate: 1 sec<br/>
Plugins enabled: CORETEMP/FREQ running in its own threads, RESUSAGE (process stats), SIGAR</p>

**Comment by hkbai** [comment]
<b><i>[author="vpedabal", created="Tue, 16 Jun 2015 19:20:37 +0000"]</i></b>
<p>Hi David,</p>

<p>This is an excellent report. Can you also run a test on how the memory is consumed without per-thread sampling?</p>

**Comment by hkbai** [comment]
<b><i>[author="lrrajesh", created="Wed, 17 Jun 2015 01:02:09 +0000"]</i></b>
<p>Hi David,</p>

<p>I ran a simple test with per-thread sampling enabled for coretemp and freq and used a sample rate 1 sec and ran a top on orcmd to see if the there is any memory leak.<br/>
I was surprised there was no memory leak shown from the  top command on orcmd it seems to be running stable at the same size for a while. It increaments the memory every 5 secs and decrements the memory after it is done.</p>

<p>I have both coretemp and freq running in separate threads and sampling at 1 sec rate.</p>

<p>You probably found a memory leak issue either in database or in sigar plugin.<br/>
I will investigate this further to root cause this.</p>

<p>Thanks<br/>
~Rajesh</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Wed, 17 Jun 2015 16:13:31 +0000"]</i></b>
<p>After running the same test without perthread sampling I can confirm that the issue is still present as shown by the new set plots.<br/>
/opt/orcm_test/bin/orcmd -s /home/test/TOMATEperf-prev-0.3/data/orcm-master4.xml -omca sensor heartbeat,resusage,sigar,coretemp -omca sensor_resusage_log_process_stats true -omca sensor_base_sample_rate 1 -omca db_odbc_table data_sample -omca db_odbc_user orcmuser:orcmpassword -omca db_odbc_dsn orcmdb_psql -omca db_base_verbose 10 -omca db_postgres_table data_sample_raw -omca db_postgres_uri localhost:5432 -omca db_postgres_user orcmuser:orcmpassword -omca db_postgres_database orcmdb</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Wed, 17 Jun 2015 19:33:55 +0000"]</i></b>
<p>vsize memory usage when running without DB. Seems that the issue is not present when using the print component.</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Thu, 18 Jun 2015 15:20:03 +0000"]</i></b>
<p>I did another test, but this time the DB was not running in the same node with the AG. I'm attaching the relevant plots for node c01 (Aggregator node)</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Thu, 18 Jun 2015 15:28:17 +0000"]</i></b>
<p>These are the metrics on the node where the DB was running.</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Mon, 29 Jun 2015 16:18:59 +0000"]</i></b>
<p>This issue will be closed and tracked at a component level as in <a href="https://tcgsw-jira.amr.corp.intel.com/browse/CSS-304" title="[CORETEMP] in aggregator node consumes memory at an approximate rate of 1.1 MB/min " class="issue-link" data-issue-key="CSS-304">ORCM-304</a></p>

**Comment by noahv** [comment]
Fixed by the following and other prior memory leak fixes:

commit 611cc75e04c0ae0f94d672629291fed91df62a1f
Author: Vineet Pedaballe <vineet.pedaballe@intel.com>
Date:   Thu Jun 18 09:21:38 2015 -0700
 
    More memory leak fixes
