### ISSUE TITLE
DB Purge by partition not dropping all the tables

### ISSUE THREAD

**Issue by hkbai** [open-mpi/orcm#185]
<b><i>[reporter="rrochavi", created="Mon, 20 Jul 2015 17:26:37 +0000", resolved="Fri, 31 Jul 2015 17:10:43 +0000"]</i></b>
<p>The script that handles partitions is just dropping the just expired partition. If you make a pause or change the expiration interval you may end with partitions that will never be deleted (unless you do it manually).<br/>
The insert trigger assumes that all the nodes are time synchronized, that's why it creates first the partitions and then drops the expired partitions but, if for some reason (testing / special purpose) you have nodes that are not synchronized this could end on an ilegal insertion (fatal error) in a non existing (just deleted) partition.<br/>
The delete/drop statement for expired data, takes the date from the incoming data as the reference for calculating the deleting time interval. If the incoming data has a wrong / different date it could end deleting data that is still valuable.</p>

**Comment by hkbai** [comment]
<b><i>[author="dclaudio", created="Fri, 31 Jul 2015 17:10:43 +0000"]</i></b>
<p>Agreed with Rajesh in pushing this to next release as it is not a critical issue. Hong will make changes regarding to the way in which expired partitions are dropped and then a new code review will be submitted.</p>

**Comment by htquach** [comment]
The Database purge by partition code has been updated to remove expired records as defined by the purge policy.  This makes the truly expired partitions to be empty, and the purge partition code will remove all empty partition.  

The change can be verify at the commit a4dace3ae8bc597a8b0bab4010d5d694d8588b98 in this repo.
