### ISSUE TITLE
Incorrect configure.m4 logic ...?

### ISSUE THREAD

**Issue by DarrenPR** [open-mpi/orcm#23]
Not sure if this is truly an issue or not, but I'll put it here so it's known.

I've heard it mentioned a couple times that the idea behind whether or not something is going to be included in ORCM during configure time is supposed to be that it will search for the support (headers, installed binaries, etc.) and if it finds it, that particular component will be included in the installation unless explicitly told not to within the platform file.

The current implementation in the configure.m4 files seems to have the opposite logic, where it needs to  be explicitly told to include something like IPMI, sigar or ODBC and if it doesn't find the support for it after being told to be included, then it will error.

I don't know whether the first or second configure.m4 logic is correct, nor do I know enough about configure.m4 files to know how to change the logic around to match the correct logic. Hoping to get some clarification and/or insight on this.

**Comment by vpedabal** [comment]
Fixed in sigar as well
