### ISSUE TITLE
General errors when building orcm during configure and make phases

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#78]
When building orcm from source, configure step does not complete if the required dependencies for a given plugin are not found e.g. sigar, unixODBC, etc. and thus is not possible to build orcm. This may discourage someone to build and use orcm whenever they don't have the required hardware or  package for a given orcm plugin. Suppose a situation when my hardware doesn't support a theoretical ipmi plugin at all, one can enable or disable a plugin during the configure phase so both step and make phases succed.

As an example of the above, if for some reason I haven't installed  the required packages for a given plugin e.g. sigar or coretemp the configure would show something like this:

--- MCA component sensor:sigar (m4 configuration macro)
checking for MCA component sensor:sigar compile mode... dso
checking sigar.h usability... no
checking sigar.h presence... no
checking for sigar.h... no
configure: WARNING: SIGAR SENSOR SUPPORT REQUESTED
configure: WARNING: BUT REQUIRED LIBRARY OR HEADER NOT FOUND
configure: error: CANNOT CONTINUE

In other cases, the configure step will complete but it will show errors during the make step when orcm tries to build a component e.g. sensor_nodepower it displays an error like this during the make step

make[2]: *** [sensor_nodepower.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/export/orcm/build/orcm/mca/sensor/nodepower'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/export/orcm/build/orcm'
make: *** [all-recursive] Error 1

However if I disable the component by editing/adding the following lines into the platform file
with_sigar=no
with_nodepower=no
then I can still build and use orcm 

I think this should be documented so users are not discouraged from using and trying orcm even though they won't be fully enjoying its functionality.

**Comment by noahv** [comment]
Does not reproduce with Centos or Suse.  Closing this very old issue.
