### ISSUE TITLE
RPM spec file is buildrequires for libsigar

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#82]
rpmbuild --rebuild open-rcm-0.5.0-1.src.rpm needs to have a buildrequires for libsigar.

Instead, we don't catch this until trying to rpm install:
<pre>
error: Failed dependencies:
        libsigar.so.0()(64bit) is needed by open-rcm-0.5.0-1.x86_64
</pre>

After correcting the missing dependency, trying to install still fails because we actually need to re-run the rpmbuild step.

Thanks,

  -- Noah

**Comment by benmcclelland** [comment]
fixed in master by commit 31a057e

**Comment by noahv** [comment]
Fix verified.
