### ISSUE TITLE
orcm won't build with libtool 2.4.3 or greater

### ISSUE THREAD

**Issue by vlopezsantoyo** [open-mpi/orcm#84]
Trying to compile orcm after cloning the repo will fail due to the following error:

[victor@karate orcm]$ make
Making all in config
make[1]: Entering directory `/vol/orcm/git/orcm/config'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/vol/orcm/git/orcm/config'
Making all in contrib
make[1]: Entering directory `/vol/orcm/git/orcm/contrib'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/vol/orcm/git/orcm/contrib'
Making all in opal
make[1]: Entering directory `/vol/orcm/git/orcm/opal'
Making all in include
make[2]: Entering directory `/vol/orcm/git/orcm/opal/include'
make  all-am
make[3]: Entering directory `/vol/orcm/git/orcm/opal/include'
make[3]: Leaving directory `/vol/orcm/git/orcm/opal/include'
make[2]: Leaving directory `/vol/orcm/git/orcm/opal/include'
Making all in libltdl
make[2]: Entering directory `/vol/orcm/git/orcm/opal/libltdl'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /vol/orcm/git/orcm/config/missing aclocal-1.14 -I ../../config
aclocal-1.14: error: ../../config/autogen_found_items.m4:239: file 'opal/mca/backtrace/configure.m4' does not exist
make[2]: *** [aclocal.m4] Error 1
make[2]: Leaving directory `/vol/orcm/git/orcm/opal/libltdl'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/vol/orcm/git/orcm/opal'
make: *** [all-recursive] Error 1

As a workaround the documentation can be updated to state that libtool 2.4.2 is the only version supported.

**Comment by vpedabal** [comment]
It's been identified as an autoconf bug; They're working on it and trying to fix and release a new version. Mark in the release notes.

**Comment by lrrajesh** [comment]
A fix for this is pulled in from OMPI branch. Please verify.

**Comment by noahv** [comment]
Fix verfied:

[Thu Jun 04 13:48:11 noah@linux-52om:openrcm-0.9.0a1] libtool --version
libtool (GNU libtool) 2.4.3
Written by Gordon Matzigkeit, 1996
