### ISSUE TITLE
Units of memory metrics (mem_total, mem_used, and mem_actual_free) are incorrect 

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#86]
By looking at the units logged by ORCM when monitoring the mem_total, mem_used, and mem_actual_free metrics from the sigar component. Please notice that the units are wrong. The units reported and being stored into the DB are kB when in fact they should be bytes.

Store request: sigar; values:
ctime=2014-11-13 09:04:40-0600,hostname=bertafsp-headnode,**mem_total=25126481920:kB,mem_used=959553536:kB,mem_actual_used=581255168:kB,mem_actual_free=24545226752:kB**,swap_total=8595533824:kB,swap_used=0:kB,swap_page_in=0:kB,swap_page_out=0:kB,cpu_user=0.024994:%,cpu_sys=0.099975:%,cpu_idle=99.875031:%,load0=0.090000,load1=0.040000,load2=0.010000,disk_ro_rate=0:ops/sec,disk_wo_rate=3:ops/sec,disk_rb_rate=0:bytes/sec,disk_wb_rate=34407:bytes/sec,net_rp_rate=713:packets/sec,net_wp_rate=481:packets/sec,net_rb_rate=762599:bytes/sec,net_wb_rate=54731:bytes/sec
Store request: sigar; values:
ctime=2014-11-13 09:04:41-0600,hostname=node02,**mem_total=25262882816:kB,mem_used=814952448:kB,mem_actual_used=297746432:kB,mem_actual_free=24965136384:kB,**swap_total=0:kB,swap_used=0:kB,swap_page_in=0:kB,swap_page_out=0:kB,cpu_user=0.000000:%,cpu_sys=0.008327:%,cpu_idle=99.991676:%,load0=0.000000,load1=0.000000,load2=0.000000,disk_ro_rate=0:ops/sec,disk_wo_rate=0:ops/sec,disk_rb_rate=0:bytes/sec,disk_wb_rate=0:bytes/sec,net_rp_rate=2:packets/sec,net_wp_rate=2:packets/sec,net_rb_rate=230:bytes/sec,net_wb_rate=306:bytes/sec

As a comparison the output of the free command executed in the same system is as follows:

``` 
# free -b
	total		used		free		shared	buffers		cached
 Mem:	25126371328	605167616	24521203712	0	10280960	144408576
 -/+ buffers/cache:	450228224	24676143104
 Swap:	8595533824	0	8595533824
```
This issue is same no matter if the data logged corresponds to an aggregator or orcm daemon, and has been observed in both RHEL 6 and SLES 11 SP3

**Comment by vpedabal** [comment]
Fixed in master; In plan to merge into 1.0v branch
