### ISSUE TITLE
Amount of data logged into the DB is different for aggregator and compute daemons

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#90]
1. When running ORCM with one aggregator and several compute nodes, I have observed that the amount of data logged for the aggregator and compute daemons differs considerably. This usually depends on the component being logged. So far, most of the observations have been performed when logging coretemp and frequency data. This issue is also observed when using longer logging periods. In a 10 min period, the ratio of rows stored for the aggegator vs rows stored for compute daemons is 4.82:1 In a 20 min period, ratio increases to 5.36:1. Of course we can expect the amount of data logged per daemon to differ because hardware could vary from daemon to daemon, for instance the aggregator could have 12 cores whereas and computed daemon 16 cores, however this is not the case in our test, because hardware is identical across all nodes, so we expect that the amount of data logged into the DB to be same. 
2. This also means that the monitoring time for aggregator and compute daemons, which at least in principle should be the same, is not always equal. Consider a monitoring time of 10 mins. Usually the amount of data logged by the aggregator into the DB should be close to this period of time. However, in the case of computed daemons the amount of data logged into the DB can be as low as 4 mins, we report an observation in which data was written into the DB by the aggregator during a period of 10 mins whereas in the case of compute daemons the period of data written into the DB was only 40 secs!. This behaviour is undesirable because ORCM could miss important monitoring data for debugging a node or set of nodes in the case an unexpected failure or shutdown. 
3. There is no way to test if the data is already on the aggregator and queued to be written into the DB or if it is queued on the compute daemon waiting to be sent and acknowledged by the aggregator. 

Below I attaching some data obtained when running ORCM on RHEL 6 and SLES 11 SP3
**Amount of data written to the DB when running ORCM in SLES 11 SP3 and monitoring coretemp!**
```
Node	Rows fetched	Start time	Stop time
headnode	22981	10:39:58	10:47:57
node01	216	10:40:00	10:40:40
node02	216	10:40:00	10:40:40
node03	216	10:40:03	10:40:43
node04	216	10:40:00	10:40:41
node05	216	10:40:01	10:40:41
node06	216	10:39:59	10:40:39
node07	216	10:40:02	10:40:42
node08	216	10:40:00	10:40:40
node09	216	10:40:00	10:40:40
node10	216	10:40:02	10:40:42
node11	216	10:40:03	10:40:43
node12	432	10:39:59	10:40:39
node13	432	10:40:04	10:40:44
node14	216	10:40:02	10:40:42
node15	216	10:40:03	10:40:43
node16	216	10:40:03	10:40:43
node17	216	10:40:01	10:40:41
node18	216	10:40:02	10:40:42
node19	216	10:40:01	10:40:41
node20	216	10:39:59	10:40:39
node21	216	10:40:00	10:40:40
node22	216	10:40:02	10:40:42
node23	216	10:40:02	10:40:42
node24	216	10:40:01	10:40:41
node25	216	10:40:02	10:40:42
node26	432	10:40:01	10:40:41
node27	432	10:40:03	10:40:43
node28	216	10:40:02	10:40:42
node29	216	10:40:02	10:40:42
node30	216	10:40:02	10:40:42
node31	432	10:40:02	10:40:42
node32	216	10:40:00	10:40:40
```
**Amount of data written to the DB when running ORCM in SLES 11 SP3 and monitoring coretemp**
```
Node	Rows fetched	Start time	Stop time
headnode	5993	13:45:32	14:04:43
node01	1118	13:45:34	13:49:05
node02	1118	13:45:34	13:49:05
node03	1118	13:45:35	13:49:05
node04	1118	13:45:34	13:49:05
node05	1118	13:45:34	13:49:05
node06	1118	13:45:34	13:49:04
node07	1118	13:45:35	13:49:05
node08	1118	13:45:34	13:49:05
node09	1118	13:45:34	13:49:05
node10	1118	13:45:35	13:49:05
node11	1118	13:45:35	13:49:05
node12	1118	13:45:34	13:49:04
node13	1118	13:45:35	13:49:05
node14	1118	13:45:35	13:49:05
node15	1118	13:45:35	13:49:05
node16	1118	13:45:35	13:49:05
node17	1118	13:45:35	13:49:05
node18	1118	13:45:35	13:49:05
node19	1118	13:45:34	13:49:05
node20	1118	13:45:34	13:49:04
node21	1118	13:45:34	13:49:05
node22	1118	13:45:35	13:49:05
node23	1118	13:45:35	13:49:05
node24	1118	13:45:35	13:49:05
node25	1118	13:45:35	13:49:05
node26	1118	13:45:35	13:49:05
node27	1118	13:45:35	13:49:05
node28	1118	13:45:35	13:49:05
node29	1118	13:45:35	13:49:05
node30	1118	13:45:35	13:49:05
node31	1118	13:45:35	13:49:05
node32	1118	13:45:34	13:49:05
```
**Amount of data written to the DB when running ORCM in RHEL 6 and monitoring frequency**
```
Node	Rows fetched	Start time	Stop time
bertafsp-headnode	2856	16:23:06	16:25:04
node01	456	16:23:11	16:24:41
node02	456	16:23:11	16:24:41
```

**Comment by forzaclaudio** [comment]
I can confirm that this issue is still present in v0.7 and master with their corresponding schemas. We have performed tests for the SIGAR and RESUSAGE components running on SLES 12. We focused on these two componentes because together, they log the most varied monitoring data into the database. In the case of SIGAR, at the end of the test which have a 10-minute duration, we observe that we are missing 30 seconds worth of monitoring data in the case of the aggregator daemon (AG) as shown in Figure 1. In the case of the aggregators, this issue is even worse because the amount of data missing is approximately 8.5 mins, see Figures 2 and 3. In the case of RESUSAGE, the issue is milder because the amount of missing data is only a few seconds for the AG (see Figure 4) and approximately 2 mins for the CNs (see Figures 5 and 6)

**SIGAR**
![headnodeorcmdb-sigardiskrbtotal](https://cloud.githubusercontent.com/assets/8369713/5860658/79609440-a228-11e4-8b94-56183d25b351.png)
**Figure 1.** Data written into the DB during ORCM execution (aggregator daemon) for 10 minutes,  metric analyzed is the total amount of bytes written to disk

![node01orcmdb-sigardiskrbtotal]
(https://cloud.githubusercontent.com/assets/8369713/5860659/7f001bdc-a228-11e4-9fec-b30aeb5a0609.png)
**Figure 2.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes, i.e. node01. The observed negative values constitute another issue which has been already reported in #144. Metric analyzed is the total amount of bytes written to disk

![node32orcmdb-sigardiskrbtotal](https://cloud.githubusercontent.com/assets/8369713/5860663/850cfc2a-a228-11e4-9266-ad509e2e25a6.png)
**Figure 3.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes, i.e. node32. The observed negative values constitute another issue which has been already reported in #144. Metric analyzed is the total amount of bytes written to disk

**RESUSAGE**
![headnodeorcmdb-resusagefreemem](https://cloud.githubusercontent.com/assets/8369713/5861163/6651c118-a22c-11e4-928b-ca7f744d801e.png)
**Figure 4.** Data written into the DB during ORCM execution (aggregator daemon) for 10 minutes,  metric analyzed is the amount of free memory during the execution of an HPC workload


![node01orcmdb-resusagefreemem](https://cloud.githubusercontent.com/assets/8369713/5861165/6a908f02-a22c-11e4-8818-02fd421b815c.png)
**Figure 5.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes, i.e. node01. Metric analyzed is the amount of free memory during the execution of an HPC workload.


![node20orcmdb-resusagefreemem](https://cloud.githubusercontent.com/assets/8369713/5861168/73d3552c-a22c-11e4-8af3-b4b13a9544d4.png)
**Figure 6.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes, i.e. node20. Metric analyzed is the amount of free memory during the execution of an HPC workload.

**Comment by forzaclaudio** [comment]
I ran a test of ORCM writting logging data to the DB with all components activated, under **IDLE** conditions for all nodes in a 32-node cluster and I've got the following results:

**CORETEMP**
![headnodeorcmdb-coretemp](https://cloud.githubusercontent.com/assets/8369713/5883226/fcc6d770-a315-11e4-8d91-2227ae7d2249.png)
**Figure 1.** Data written into the DB during ORCM execution (aggregator daemon) for 1 hour.  The amount of missing data is aproximately **5.5 mins** for the CORETEMP component data.

![node01orcmdb-coretemp](https://cloud.githubusercontent.com/assets/8369713/5883269/970d771c-a316-11e4-81f3-c61572055ee2.png)
**Figure 2.** Data written into the DB during ORCM execution (compute daemon) for 1 hour i.e. node01 . The amount of missing data for the CORETEMP component is aproximately **58 mins**!

![node31orcmdb-coretemp](https://cloud.githubusercontent.com/assets/8369713/5883359/2c7f7188-a317-11e4-9b6e-0dd4a92e6320.png)
**Figure 3.** Data written into the DB during ORCM execution (compute daemon) for 1 hour i.e. node31 . The amount of missing data for the CORETEMP component is aproximately **59 mins** !

I'm still processing the data for the remaining components, e.g. SIGAR, FREQUENCY, NODEPOWER, etc. so I will post them as soon as I can.

**Comment by avilcheslopez** [comment]
Fix for #104 should help fix this issue.  Fix pushed into master and release branch.

**Comment by forzaclaudio** [comment]
I did a small indirect study of the performance of the ORCM database (DB) as a function of nodes for a single component e.g. **FREQUENCY**. We chose this component because the amount of values that need to be written into the DB ares comparable to other components e.g. **SIGAR**, especially for case where the compute nodes feature a high number of cores and support for hyperthreading. The study consisted in launching on ORCM aggregator (AG) daemon and one or more ORCM compute (CN) daemons and then stopping all the daemons at exactly 10 mins. By looking at the timestamp of the latest data written in the DB we can determine the average lag time between the data being sampled and the time at which data are successfully written into the DB. This provides us with an insight of the expected performance of the DB as the number of nodes to be monitored grows. 

**Agreggator node**
![ag lag time steady](https://cloud.githubusercontent.com/assets/8369713/5962769/ce386866-a7ab-11e4-9b31-01dc793836f8.png)
**Figure 1** Observed lag time of monitoring data from the AG being written into the DB. We observe that the lag time is about **9 seconds** and remains constant until a number of 8 nodes. 

![ag lag time linear](https://cloud.githubusercontent.com/assets/8369713/5962807/141564d8-a7ac-11e4-9a98-e235915103ee.png)
**Figure 2**  Observed lag time of monitoring data from the AG being written into the DB for a number of nodes larger than 8. If we assume a linear behaviour then the lag time is expected to increase in a factor of approximately **17x** for each additional node added to the system. 

**Compute nodes**
![cns lag time](https://cloud.githubusercontent.com/assets/8369713/5962941/40895b90-a7ad-11e4-8e40-dc4b93e9f02a.png)
**Figure 3** Observed lag time of monitoring data from the CNs being written into the DB. We observe that the lag time increases considerably for a number of nodes larger than 8. In the best case scenario, the lag time is expected to increase by a factor of **20x** for each additional node added to the system

![cns lag time linear](https://cloud.githubusercontent.com/assets/8369713/5962945/49f4ca98-a7ad-11e4-968d-00387aa7b23b.png)
**Figure 4** Observed lag time of monitoring data from the CNs being written into the DB. We can see that the behaviour of lag is approximately linear up to a number of 16 nodes. In this range the lag time increases at a rate of about **1.5 seconds per node**

Bear in mind that this study was done for a single component. It is expected that the actual values are slightly higher as the number of components to monitor increase, however it is reasonable to expect only minor proportional corrections

**Comment by forzaclaudio** [comment]
I forgot to mention that the above data was obtained at a 5-sec rate. A linear proportional dependence on the sampling rate is also expected

**Comment by forzaclaudio** [comment]
In order to reduce the amount of lag in the writting of monitoring data to the DB in systems with 32-nodes, a sampling time of 1 min should be used for a lag of 4 datasamples in the compute daemons and 2 min for a lag of 3 datasamples. No lag is expected to occur in the aggregator daemon

**Comment by forzaclaudio** [comment]
Closing it because with the new DB schema and when using the postgres plugin in version v0.9 the issue is not present up to 13 nodes (1 AG + 12 CN)
