### ISSUE TITLE
ORCMD - Inventory Gathering - Missing to log baseboard Manufacturer date

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#96]
ORCMD is not logging Baseboard manufacturer date which is required according Inventory_Control_SRS.docx. See current output example:

[pedro@centospedro bin]$ sudo ./orcmd -omca sensor dmidata -omca sensor_base_collect_inventory true
[centospedro.zpn.intel.com:28122] 
******************************
Mon Jan  5 07:33:51 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: update_node_features; data:
hostname=centospedro,product_uuid=9D556D01-B540-11DF-BD28-000BAB01F3E0,bb_vendor=Intel Corporation,bb_model=S5520SC,bb_version=E30682-355,bb_serial=QSHV03400472,bios_vendor=Intel Corp.,bios_version=S5500.86B.01.X2.0059.091520111722,bios_release_date=09/15/2011,cpu_vendor=GenuineIntel,cpu_family=6,cpu_model_number=44,cpu_model=Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz

**Comment by vpedabal** [comment]
The inventory collection depends on the DMI Tables to populate a manufactured date, it looks like it doesn't get stored in the tables. In my opinion it was an oversight while gathering the requirements, so the solution is to remove this term from the SRS entirely.

**Comment by piniguez** [comment]
Looks like baseboard information is already available through IPMI method. Can we dump it for -omca sensor_base_collect_inventory true?

See example of ipmi output:
primary_key=ipmi,ctime=2015-01-08 13:42:28-0600,nodename=centospedro,BBmanuf_date=08/24/10,BBmanuf=Intel Corporation,BBname=S5520SC,BBserial=QSHV03400472,BBpart=E30682-355

**Comment by vpedabal** [comment]
No we cannot, this was my initial implementation as part of the sensor metrics, before we decided to have a separate implementation for inventory.

I am considering deprecating it after this release and collect that information only if inventory collection is enabled.

**Comment by piniguez** [comment]
ok, thanks. So assuming this issue is now closed for good :)

**Comment by vpedabal** [comment]
Hi Pedro, I 'JUST' figured out how to add this :+1:  Until you posted the information IPMI was already collecting as part of metrics I forgot it was the FRU which stored manufactured date. I sent a review request out to the team and will push it to master once it is approved. Thanks for the pointing this out :smiley:

**Comment by piniguez** [comment]
Fix verified, ORCMD Inventory Gathering now reports a date.
On the other hand the day in the date is wrong however this is reported on issue #143
