### ISSUE TITLE
Column ordering changing between versions in some components

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#98]
I realized that in the log line corresponding to coretemp readings. The position of the Physical Id temp was changed from the start of the number of cores in a socket to the end of it, breaking all functionality based on the original ordering in version 0.5. 

Order in version 0.5 was **Physical id i, Cores j, Physical id i+1, Cores j, etc**
where i indicates the socket number in the motherboard and j the core number which goes from 0 to the total number of cores in the system

As an example of the above, see the following logs 

ORCM log line from current version (january 2015)
primary_key=coretemp,ctime=2015-01-07 11:59:58-0800,hostname=headnode,**core 0=30.000000:degrees C**,core 1=23.000000:degrees C,core 2=21.000000:degrees C,core 3=25.000000:degrees C,core 4=25.000000:degrees C,core 5=30.000000:degrees C,core 6=27.000000:degrees C,core 7=35.000000:degrees C,core 8=27.000000:degrees C,core 9=27.000000:degrees C,core 10=27.000000:degrees C,core 11=22.000000:degrees C,**Physical id 0=35.000000:degrees C**,core 12=18.000000:degrees C,core 13=21.000000:degrees C,core 14=26.000000:degrees C,core 15=25.000000:degrees C,core 16=30.000000:degrees C,core 17=20.000000:degrees C,core 18=18.000000:degrees C,core 19=24.000000:degrees C,core 20=25.000000:degrees C,core 21=21.000000:degrees C,core 22=22.000000:degrees C,core 23=26.000000:degrees C,Physical id 1=30.000000:degrees C

ORCM log line from version 0.5
ctime=2014-10-10 14:10:23-0700,hostname=headnode,**core0=26.000000:degrees C**,core1=20.000000:degrees C,core2=21.000000:degrees C,core3=23.000000:degrees C,core4=24.000000:degrees C,core5=29.000000:degrees C,core6=24.000000:degrees C,core7=32.000000:degrees C,core8=25.000000:degrees C,core9=25.000000:degrees C,core10=26.000000:degrees C,core11=21.000000:degrees C,core12=21.000000:degrees C,**core13=23.000000:degrees C**,core14=28.000000:degrees C,core15=25.000000:degrees C,core16=30.000000:degrees C,core17=21.000000:degrees C,core18=18.000000:degrees C,core19=23.000000:degrees C,core20=25.000000:degrees C,core21=21.000000:degrees C,core22=23.000000:degrees C,core23=26.000000:degrees C

Please note that labeling in version 0.5: **core0** corresponds to **Physical Id 0** and **core 13** to **Physical Id 13**

**Comment by vpedabal** [comment]
0.5 version wasn't recording the physical ID temperature at all. It was defeatured since the the implementation of recording coretemp was slightly faulty. Post-0.5 release I fixed the issue and re-enabled measuring the pysical ID (package) temperatures. In any case, I don't see it as a bug, but rather an architectural issue.

**Comment by rhc54** [comment]
Maybe the solution would be to change the "physical id" label to "package" so it is clearer that these are the package temperatures, and not core temps?

**Comment by vpedabal** [comment]
Ya, I was also thinking to do the same when I change the re-ordering. But if changing the label will make this clearer and fix the issue, it sure will save some time for me. What say @forzaclaudio :wink:?

**Comment by forzaclaudio** [comment]
For the time being the name is not that important, is the ordering what is breaking the validation scripts. It would be nice to agree and commit to a standard ordering and "set it in stone". Post-0.5 release was an ordering that made the most sense. Physical id i, Cores j, Physical id i+1, Cores j, etc If you want to keep the current ordering is fine but we need to make sure that it won't change for as long as possible e.g. until version 2.0 or 3.0

**Comment by lrrajesh** [comment]
Basically what you are asking for is backward compatibility for the tool output moving forward which I think is reasonable ask. We should consider supporting backward compatibility for all our tool output, ABI for the library and for the database schema till the next major version change.

**Comment by vpedabal** [comment]
Technically, collecting package temperatures wasn't available in the previous release. You should consider this as a new feature, but irrespective of that, I'll see if I can change this to resolve your test issue.

Also to be honest the test cases should use the 'key' in the "key=value" format in identifying each item and verifying if it is correct or not rather than hanging on to a fixed position. Usually coretemp & freq might display the metrics in a fixed order, but there are chances when the IPMI metrics' ordering could potentially change. Just a suggestion.

**Comment by rhc54** [comment]
Agreed - creating a validation tool that is locked to a specific ordering would not be a good idea as it is too fragile. You need to split the stream into key-value pairs and check those.

**Comment by forzaclaudio** [comment]
Completely agree that the funcionality to lookup into a log line by key-value is a must in a validation tool. But I was thinking of a third party trying to get some functionality out of ORCM's current monitoring capabilities. If we don't call out or adhere to some sort of standard when printing out this info, we are going to be embedding complexity into something trivial as the ordering of some fields in a log line. Third parties planning to use ORCM's monitoring capabilities should not require the ultimate line parser just to know a few temperature readings and do something useful with them. The format of the lines in orcmd line have changed so much in between minor releases that is a pain in the neck to keep up with the changes and to be able to extract any funcionality out of them. In summary, we must find a way to ensure that new features don't break any existing functionality neither in the present nor the future.

**Comment by rhc54** [comment]
Now that doesn't make any sense. The print module is there solely for debugging purposes and would never be operational in a production environment. This is why any third party tool is supposed to go thru the database, not try to parse some debug output.

What we are talking about here is just the appropriate behavior for a validation tool. We could have the validation tool go thru the database, if we want to require that the database be part of the validation. Until now, I believe people wanted it kept separate, and so you folks were working off the debug output. This is fine (I really don't care), but hardly applies to production.

**Comment by forzaclaudio** [comment]
Ok, agree it will never make it into a product in production. But, how do you make sure that the info stored in the DB is correct in both their values and amount? Are you aware of issue #90? There is not point on relying on the data stored in the DB if we cannot be 100% sure that the data are right. That's why we shouldn't rely on the data stored in the DB until we can make sure that not only the data are 100% reliable but also, the amount is right. But guess what, the only way to do that is using the debug ouput. Let's assume that the data in the DB is 100% legit for validation purposes, i.e. it truly reflects the state of the whole system, why is ORCM only logging data for 2 minutes when it should be logging data for 10 minutes. How do I validate the 8 minutes worth of monitoring data missing? How do I know fault is this? Is ORCM's fault or a problem with the DB or the DB manager? Maybe you don't @rhc54, but I think someone should care about this.

**Comment by rhc54** [comment]
Sigh...calm down, dude. Nobody said they didn't care about it. What you need for validation is to be using a defined test vector out of each sensor, not raw data that defies validation. If people look closely, you'll see that I had defined test vectors for the sensors I wrote for just this reason - assuming they haven't been removed (sadness if so). All you had to do was specify an MCA param indicating that you wanted the test vector to be provided, and then you _know_ what the output should be and can test against it.

So the problem here isn't with ordering in the print statement. The problem is that people didn't include a test vector capability. Let's address that problem instead, okay?

**Comment by forzaclaudio** [comment]
No worries, I'm not taking this personally. I didn't have idea that the test vectors existed. Had this been documented somewhere, this conversation would have never happened. Thanks for the heads up, I'll start chasing these test vectors. Thanks for taking the time of looking at this issue.

**Comment by benmcclelland** [comment]
It looks like these test vectors have not been fully implemented in all the
components.  It appears that sigar might have a good chance of working, but
probably not any of the others.
